# Form implementation generated from reading ui file 'org_newmsg.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 750)
        self.msg_widget = QtWidgets.QWidget(parent=Form)
        self.msg_widget.setGeometry(QtCore.QRect(270, 50, 451, 661))
        self.msg_widget.setStyleSheet("#msg_widget {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.msg_widget.setObjectName("msg_widget")
        self.org_label = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label.setGeometry(QtCore.QRect(20, 10, 301, 41))
        self.org_label.setStyleSheet("#org_label {\n"
"    font-family: Segoe UI;\n"
"    font-size: 23px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.org_label.setObjectName("org_label")
        self.org_label_2 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label_2.setGeometry(QtCore.QRect(20, 50, 151, 41))
        self.org_label_2.setStyleSheet("#org_label_2 {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.org_label_2.setObjectName("org_label_2")
        self.close_btn = QtWidgets.QToolButton(parent=self.msg_widget)
        self.close_btn.setGeometry(QtCore.QRect(400, 20, 31, 31))
        self.close_btn.setObjectName("close_btn")
        self.line_name = QtWidgets.QLineEdit(parent=self.msg_widget)
        self.line_name.setGeometry(QtCore.QRect(20, 90, 411, 41))
        self.line_name.setStyleSheet("#line_name {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#line_name:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#line_name:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.line_name.setObjectName("line_name")
        self.org_label_3 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label_3.setGeometry(QtCore.QRect(20, 140, 141, 31))
        self.org_label_3.setStyleSheet("#org_label_3 {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.org_label_3.setObjectName("org_label_3")
        self.line_role = QtWidgets.QComboBox(parent=self.msg_widget)
        self.line_role.setGeometry(QtCore.QRect(20, 170, 411, 41))
        self.line_role.setStyleSheet("#line_role {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#line_role:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#line_role:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.line_role.setObjectName("line_role")
        self.line_role.addItem("")
        self.line_role.addItem("")
        self.line_role.addItem("")
        self.line_role.addItem("")
        self.line_role.addItem("")
        self.org_label_4 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label_4.setGeometry(QtCore.QRect(20, 210, 151, 41))
        self.org_label_4.setStyleSheet("#org_label_4 {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.org_label_4.setObjectName("org_label_4")
        self.line_role_2 = QtWidgets.QComboBox(parent=self.msg_widget)
        self.line_role_2.setGeometry(QtCore.QRect(20, 250, 411, 41))
        self.line_role_2.setStyleSheet("#line_role_2 {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#line_role:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#line_role:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.line_role_2.setObjectName("line_role_2")
        self.line_role_2.addItem("")
        self.line_role_2.setItemText(0, "")
        self.line_role_2.addItem("")
        self.line_role_2.addItem("")
        self.line_role_2.addItem("")
        self.org_label_5 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label_5.setGeometry(QtCore.QRect(20, 290, 151, 41))
        self.org_label_5.setStyleSheet("#org_label_5{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.org_label_5.setObjectName("org_label_5")
        self.line_name_2 = QtWidgets.QLineEdit(parent=self.msg_widget)
        self.line_name_2.setGeometry(QtCore.QRect(20, 330, 411, 41))
        self.line_name_2.setStyleSheet("#line_name_2 {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#line_name_2:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#line_name_2:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.line_name_2.setObjectName("line_name_2")
        self.org_label_6 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_label_6.setGeometry(QtCore.QRect(20, 380, 151, 41))
        self.org_label_6.setStyleSheet("#org_label_6 {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.org_label_6.setObjectName("org_label_6")
        self.btn_cancel = QtWidgets.QPushButton(parent=self.msg_widget)
        self.btn_cancel.setGeometry(QtCore.QRect(260, 610, 81, 31))
        self.btn_cancel.setStyleSheet("#btn_cancel {\n"
"    \n"
"    color: #c62828;              /* Red text color */\n"
"    border: 1.3px solid;\n"
"    border-radius: 8px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_cancel:hover {\n"
"    background-color: #c62828;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_cancel:pressed {\n"
"    background-color: #8e1c1c;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_ok = QtWidgets.QPushButton(parent=self.msg_widget)
        self.btn_ok.setGeometry(QtCore.QRect(350, 610, 75, 31))
        self.btn_ok.setStyleSheet("#btn_ok {\n"
"    background-color: #ffffff;   /* Button base color */\n"
"    color: #006420;              /* Text color */\n"
"    border: 1.3px solid;   /* Border color */\n"
"    border-radius: 8px;          /* Rounded corners */\n"
"    padding: 6px 20px;           /* Comfortable padding */\n"
"    font-family: Segoe UI;   /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_ok:hover {\n"
"    background-color: #006420;  /* Hover background */\n"
"    color: #ffffff;             /* Text color on hover */\n"
"}\n"
"\n"
"#btn_ok:pressed {\n"
"    background-color: #004d18;  /* Darker shade when pressed */\n"
"    border-color: #004d18;\n"
"}\n"
"")
        self.btn_ok.setObjectName("btn_ok")
        self.text_edit = QtWidgets.QTextEdit(parent=self.msg_widget)
        self.text_edit.setGeometry(QtCore.QRect(20, 430, 411, 161))
        self.text_edit.setStyleSheet("#text_edit {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#text_edit:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#text_edit:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.text_edit.setObjectName("text_edit")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.org_label.setText(_translate("Form", "New Message"))
        self.org_label_2.setText(_translate("Form", " Name"))
        self.close_btn.setText(_translate("Form", "..."))
        self.org_label_3.setText(_translate("Form", "Role"))
        self.line_role.setItemText(0, _translate("Form", "Select role"))
        self.line_role.setItemText(1, _translate("Form", "Instructor"))
        self.line_role.setItemText(2, _translate("Form", "Organization Officer"))
        self.line_role.setItemText(3, _translate("Form", "Admin"))
        self.line_role.setItemText(4, _translate("Form", "Student"))
        self.org_label_4.setText(_translate("Form", "Priority "))
        self.line_role_2.setItemText(1, _translate("Form", "Normal"))
        self.line_role_2.setItemText(2, _translate("Form", "Medium"))
        self.line_role_2.setItemText(3, _translate("Form", "Urgent"))
        self.org_label_5.setText(_translate("Form", "Subject"))
        self.org_label_6.setText(_translate("Form", "Enter message:"))
        self.btn_cancel.setText(_translate("Form", "CANCEL"))
        self.btn_ok.setText(_translate("Form", "OK"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
