
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1285, 1105)
        Form.setStyleSheet("\n"
                           "#btn_pend {\n"
                           "    background-color: #ffffff;      /* Base color: plain white */\n"
                           "    color: #333333;                 /* Text color */\n"
                           "    border: 1px solid;              /* Added border */\n"
                           "    border-radius: 10px;            /* Slightly rounded corners */\n"
                           "    padding: 8px 22px;              /* Comfortable padding */\n"
                           "    font-family: Segoe UI;          /* Modern font */\n"
                           "    font-size: 14px;\n"
                           "    font-weight: 600;\n"
                           "    cursor: pointer;                /* Pointer on hover */\n"
                           "    transition: all 0.25s ease;     /* Smooth transition */\n"
                           "}\n"
                           "\n"
                           "#btn_pend:hover {\n"
                           "    background-color: #006420;      /* Green on hover */\n"
                           "    color: #ffffff;                 /* White text on hover */\n"
                           "}\n"
                           "\n"
                           "#btn_pend:pressed {\n"
                           "    background-color: #004d18;      /* Darker green when pressed */\n"
                           "    color: #ffffff;\n"
                           "}\n"
                           "```")
        self.org_header = QtWidgets.QWidget(parent=Form)
        self.org_header.setGeometry(QtCore.QRect(130, 40, 791, 151))
        self.org_header.setStyleSheet("#org_header {\n"
                                      "    background-color: #006420;\n"
                                      "    border: 1px solid #dcdcdc;\n"
                                      "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                      "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                      "    font-family: \"Montserrat\"; /* Modern font */\n"
                                      "    font-size: 14px;\n"
                                      "    color: #333333;\n"
                                      "}\n"
                                      "\n"
                                      "#org_header:focus {\n"
                                      "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                      "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                      "}\n"
                                      "\n"
                                      "#org_header:hover {\n"
                                      "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                      "}\n"
                                      "")
        self.org_header.setObjectName("org_header")
        self.label_crit = QtWidgets.QLabel(parent=self.org_header)
        self.label_crit.setGeometry(QtCore.QRect(50, 20, 431, 41))
        self.label_crit.setStyleSheet("#label_crit {\n"
                                      "    font-family: Segoe UI;\n"
                                      "    font-size: 20px;\n"
                                      "    font-weight: bold;\n"
                                      "    color: white;\n"
                                      "    letter-spacing: 1px;\n"
                                      "}\n"
                                      "")
        self.label_crit.setObjectName("label_crit")
        self.label_header1 = QtWidgets.QLabel(parent=self.org_header)
        self.label_header1.setGeometry(QtCore.QRect(50, 60, 431, 41))
        self.label_header1.setStyleSheet("#label_header1 {\n"
                                         "    font-family: Segoe UI;\n"
                                         "    font-size: 13px;\n"
                                         "    color: white;\n"
                                         "    letter-spacing: 1px;\n"
                                         "}\n"
                                         "")
        self.label_header1.setObjectName("label_header1")
        self.org_total = QtWidgets.QWidget(parent=Form)
        self.org_total.setGeometry(QtCore.QRect(130, 210, 241, 151))
        self.org_total.setStyleSheet("#org_total {\n"
                                     "    background-color: #ffffff;\n"
                                     "    border: 1px solid #dcdcdc;\n"
                                     "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                     "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                     "    font-family: \"Montserrat\"; /* Modern font */\n"
                                     "    font-size: 14px;\n"
                                     "    color: #333333;\n"
                                     "}\n"
                                     "\n"
                                     "#org_total:focus {\n"
                                     "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                     "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                     "}\n"
                                     "\n"
                                     "#org_total:hover {\n"
                                     "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                     "}\n"
                                     "")
        self.org_total.setObjectName("org_total")
        self.label_num_pend = QtWidgets.QLabel(parent=self.org_total)
        self.label_num_pend.setGeometry(QtCore.QRect(90, 60, 81, 51))
        self.label_num_pend.setStyleSheet("#label_num_pend{\n"
                                          "    font-family: Segoe UI;\n"
                                          "    font-size: 30px;\n"
                                          "    font-weight: bold;\n"
                                          "    color: #000000;\n"
                                          "    letter-spacing: 1px;\n"
                                          "}\n"
                                          "")
        self.label_num_pend.setObjectName("label_num_pend")
        self.org_total_2 = QtWidgets.QLabel(parent=self.org_total)
        self.org_total_2.setGeometry(QtCore.QRect(40, 10, 171, 41))
        self.org_total_2.setStyleSheet("#org_total_2{\n"
                                       "    font-family: Segoe UI;\n"
                                       "    font-size: 15px;\n"
                                       "    font-weight: bold;\n"
                                       "    color: #006420;\n"
                                       "    letter-spacing: 1px;\n"
                                       "}\n"
                                       "")
        self.org_total_2.setObjectName("org_total_2")
        self.org_pend = QtWidgets.QWidget(parent=Form)
        self.org_pend.setGeometry(QtCore.QRect(400, 210, 261, 151))
        self.org_pend.setStyleSheet("#org_pend {\n"
                                    "    background-color: #ffffff;\n"
                                    "    border: 1px solid #dcdcdc;\n"
                                    "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                    "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                    "    font-family: \"Montserrat\"; /* Modern font */\n"
                                    "    font-size: 14px;\n"
                                    "    color: #333333;\n"
                                    "}\n"
                                    "\n"
                                    "#org_pend:focus {\n"
                                    "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                    "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                    "}\n"
                                    "\n"
                                    "#org_pend:hover {\n"
                                    "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                    "}\n"
                                    "")
        self.org_pend.setObjectName("org_pend")
        self.org_pend1 = QtWidgets.QLabel(parent=self.org_pend)
        self.org_pend1.setGeometry(QtCore.QRect(90, 10, 171, 41))
        self.org_pend1.setStyleSheet("#org_pend1 {\n"
                                     "    font-family: Segoe UI;\n"
                                     "    font-size: 15px;\n"
                                     "    font-weight: bold;\n"
                                     "    color: #006420;\n"
                                     "    letter-spacing: 1px;\n"
                                     "}\n"
                                     "")
        self.org_pend1.setObjectName("org_pend1")
        self.label_num_pend_2 = QtWidgets.QLabel(parent=self.org_pend)
        self.label_num_pend_2.setGeometry(QtCore.QRect(110, 60, 81, 51))
        self.label_num_pend_2.setStyleSheet("#label_num_pend_2{\n"
                                            "    font-family: Segoe UI;\n"
                                            "    font-size: 30px;\n"
                                            "    font-weight: bold;\n"
                                            "    color: #000000;\n"
                                            "    letter-spacing: 1px;\n"
                                            "}\n"
                                            "")
        self.label_num_pend_2.setObjectName("label_num_pend_2")
        self.org_reply = QtWidgets.QWidget(parent=Form)
        self.org_reply.setGeometry(QtCore.QRect(690, 210, 231, 151))
        self.org_reply.setStyleSheet("#org_reply {\n"
                                     "    background-color: #ffffff;\n"
                                     "    border: 1px solid #dcdcdc;\n"
                                     "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                     "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                     "    font-family: \"Montserrat\"; /* Modern font */\n"
                                     "    font-size: 14px;\n"
                                     "    color: #333333;\n"
                                     "}\n"
                                     "\n"
                                     "#org_reply:focus {\n"
                                     "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                     "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                     "}\n"
                                     "\n"
                                     "#org_reply:hover {\n"
                                     "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                     "}\n"
                                     "")
        self.org_reply.setObjectName("org_reply")
        self.org_reply1 = QtWidgets.QLabel(parent=self.org_reply)
        self.org_reply1.setGeometry(QtCore.QRect(80, 10, 171, 41))
        self.org_reply1.setStyleSheet("#org_reply1 {\n"
                                      "    font-family: Segoe UI;\n"
                                      "    font-size: 15px;\n"
                                      "    font-weight: bold;\n"
                                      "    color: #006420;\n"
                                      "    letter-spacing: 1px;\n"
                                      "}\n"
                                      "")
        self.org_reply1.setObjectName("org_reply1")
        self.label_num_reply = QtWidgets.QLabel(parent=self.org_reply)
        self.label_num_reply.setGeometry(QtCore.QRect(90, 60, 81, 51))
        self.label_num_reply.setStyleSheet("#label_num_reply{\n"
                                           "    font-family: Segoe UI;\n"
                                           "    font-size: 30px;\n"
                                           "    font-weight: bold;\n"
                                           "    color: #000000;\n"
                                           "    letter-spacing: 1px;\n"
                                           "}\n"
                                           "")
        self.label_num_reply.setObjectName("label_num_reply")
        self.btn_org = QtWidgets.QPushButton(parent=Form)
        self.btn_org.setGeometry(QtCore.QRect(130, 380, 191, 31))
        self.btn_org.setStyleSheet("#btn_org {\n"
                                   "    background-color: #ffffff;      /* Base color: plain white */\n"
                                   "    color: #333333;                 /* Text color */\n"
                                   "    border: 1px solid;              /* Added border */\n"
                                   "    border-radius: 10px;            /* Slightly rounded corners */\n"
                                   "    padding: 8px 22px;              /* Comfortable padding */\n"
                                   "    font-family: Segoe UI;          /* Modern font */\n"
                                   "    font-size: 14px;\n"
                                   "    font-weight: 600;\n"
                                   "    cursor: pointer;                /* Pointer on hover */\n"
                                   "    transition: all 0.25s ease;     /* Smooth transition */\n"
                                   "}\n"
                                   "\n"
                                   "#btn_org:hover {\n"
                                   "    background-color: #006420;      /* Green on hover */\n"
                                   "    color: #ffffff;                 /* White text on hover */\n"
                                   "}\n"
                                   "\n"
                                   "#btn_org:pressed {\n"
                                   "    background-color: #004d18;      /* Darker green when pressed */\n"
                                   "    color: #ffffff;\n"
                                   "}\n"
                                   "")
        self.btn_org.setObjectName("btn_org")
        self.btn_all = QtWidgets.QPushButton(parent=Form)
        self.btn_all.setGeometry(QtCore.QRect(330, 380, 91, 31))
        self.btn_all.setStyleSheet("#btn_all {\n"
                                   "    background-color: #ffffff;      /* Base color: plain white */\n"
                                   "    color: #333333;                 /* Text color */\n"
                                   "    border: none;                   /* No border for clean look */\n"
                                   "    border-radius: 10px;            /* Slightly rounded corners */\n"
                                   "      border: 1px solid; \n"
                                   "    padding: 8px 22px;              /* Comfortable padding */\n"
                                   "    font-family: Segoe UI; /* Modern font */\n"
                                   "    font-size: 14px;\n"
                                   "    font-weight: 600;\n"
                                   "    cursor: pointer;                /* Pointer on hover */\n"
                                   "    transition: all 0.25s ease;     /* Smooth transition */\n"
                                   "}\n"
                                   "\n"
                                   "#btn_all:hover {\n"
                                   "    background-color: #006420;      /* Green on hover */\n"
                                   "    color: #ffffff;                 /* White text on hover */\n"
                                   "}\n"
                                   "\n"
                                   "#btn_all:pressed {\n"
                                   "    background-color: #004d18;      /* Darker green when pressed */\n"
                                   "    color: #ffffff;\n"
                                   "}\n"
                                   "")
        self.btn_all.setObjectName("btn_all")
        self.btn_pend = QtWidgets.QPushButton(parent=Form)
        self.btn_pend.setGeometry(QtCore.QRect(430, 380, 101, 31))
        self.btn_pend.setObjectName("btn_pend")
        self.btn_reply = QtWidgets.QPushButton(parent=Form)
        self.btn_reply.setGeometry(QtCore.QRect(540, 380, 91, 31))
        self.btn_reply.setStyleSheet("#btn_reply {\n"
                                     "    background-color: #ffffff;      /* Base color: plain white */\n"
                                     "    color: #333333;                 /* Text color */\n"
                                     "    border: 1px solid;              /* Added border */\n"
                                     "    border-radius: 10px;            /* Slightly rounded corners */\n"
                                     "    padding: 8px 22px;              /* Comfortable padding */\n"
                                     "    font-family: Segoe UI;          /* Modern font */\n"
                                     "    font-size: 14px;\n"
                                     "    font-weight: 600;\n"
                                     "    cursor: pointer;                /* Pointer on hover */\n"
                                     "    transition: all 0.25s ease;     /* Smooth transition */\n"
                                     "}\n"
                                     "\n"
                                     "#btn_reply:hover {\n"
                                     "    background-color: #006420;      /* Green on hover */\n"
                                     "    color: #ffffff;                 /* White text on hover */\n"
                                     "}\n"
                                     "\n"
                                     "#btn_reply:pressed {\n"
                                     "    background-color: #004d18;      /* Darker green when pressed */\n"
                                     "    color: #ffffff;\n"
                                     "}\n"
                                     "")
        self.btn_reply.setObjectName("btn_reply")
        self.combo_prio = QtWidgets.QComboBox(parent=Form)
        self.combo_prio.setGeometry(QtCore.QRect(640, 380, 101, 31))
        self.combo_prio.setStyleSheet("#combo_prio {\n"
                                      "    background-color: #ffffff;\n"
                                      "    border: 1px solid #dcdcdc;\n"
                                      "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                      "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                      "    font-family: \"Montserrat\"; /* Modern font */\n"
                                      "    font-size: 14px;\n"
                                      "    color: #333333;\n"
                                      "}\n"
                                      "\n"
                                      "#combo_prio:focus {\n"
                                      "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                      "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                      "}\n"
                                      "\n"
                                      "#combo_prio:hover {\n"
                                      "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                      "}\n"
                                      "")
        self.combo_prio.setObjectName("combo_prio")
        self.combo_prio.addItem("")
        self.combo_prio.addItem("")
        self.combo_prio.addItem("")
        self.combo_prio.addItem("")
        self.widget_main = QtWidgets.QWidget(parent=Form)
        self.widget_main.setGeometry(QtCore.QRect(130, 420, 791, 591))
        self.widget_main.setStyleSheet("#widget_main {\n"
                                       "    background-color: #ffffff;\n"
                                       "    border: 1px solid #dcdcdc;\n"
                                       "    border-radius: 6px;        /* Slightly rounded corners */\n"
                                       "    padding: 8px 12px;         /* Comfortable inner spacing */\n"
                                       "    font-family: \"Montserrat\"; /* Modern font */\n"
                                       "    font-size: 14px;\n"
                                       "    color: #333333;\n"
                                       "}\n"
                                       "\n"
                                       "#widget_main:focus {\n"
                                       "    border: 1px solid #006420; /* Highlight border on focus */\n"
                                       "    background-color: #f9f9f9; /* Slightly lighter background */\n"
                                       "}\n"
                                       "\n"
                                       "#widget_main:hover {\n"
                                       "    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
                                       "}\n"
                                       "")
        self.widget_main.setObjectName("widget_main")
        self.org_label = QtWidgets.QLabel(parent=self.widget_main)
        self.org_label.setGeometry(QtCore.QRect(10, 0, 231, 41))
        self.org_label.setStyleSheet("#org_label {\n"
                                     "    font-family: Segoe UI;\n"
                                     "    font-size: 18px;\n"
                                     "    font-weight: bold;\n"
                                     "    color: #006420;\n"
                                     "    letter-spacing: 1px;\n"
                                     "}\n"
                                     "")
        self.org_label.setObjectName("org_label")
        self.line = QtWidgets.QFrame(parent=self.widget_main)
        self.line.setGeometry(QtCore.QRect(0, 40, 791, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_crit.setText(_translate("Form", "Internal Messaging and Inquiry center"))
        self.label_header1.setText(_translate("Form", "Student Organization * Officer View"))
        self.label_num_pend.setText(_translate("Form", "23"))
        self.org_total_2.setText(_translate("Form", "TOTAL MESSAGES"))
        self.org_pend1.setText(_translate("Form", "PENDING"))
        self.label_num_pend_2.setText(_translate("Form", "17"))
        self.org_reply1.setText(_translate("Form", "REPLIED"))
        self.label_num_reply.setText(_translate("Form", "67"))
        self.btn_org.setText(_translate("Form", "New Messages"))
        self.btn_all.setText(_translate("Form", "All"))
        self.btn_pend.setText(_translate("Form", "Pending"))
        self.btn_reply.setText(_translate("Form", "Replied"))
        self.combo_prio.setItemText(0, _translate("Form", "Priority"))
        self.combo_prio.setItemText(1, _translate("Form", "New Item"))
        self.combo_prio.setItemText(2, _translate("Form", "New Item"))
        self.combo_prio.setItemText(3, _translate("Form", "New Item"))
        self.org_label.setText(_translate("Form", "Organization Messages"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())