# Form implementation generated from reading ui file 'org_msgdet.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1002, 886)
        self.msg_widget = QtWidgets.QWidget(parent=Form)
        self.msg_widget.setGeometry(QtCore.QRect(140, 50, 581, 731))
        self.msg_widget.setStyleSheet("#msg_widget {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.msg_widget.setObjectName("msg_widget")
        self.org_header1 = QtWidgets.QLabel(parent=self.msg_widget)
        self.org_header1.setGeometry(QtCore.QRect(30, 10, 301, 41))
        self.org_header1.setStyleSheet("#org_header1 {\n"
"    font-family: Segoe UI;\n"
"    font-size: 23px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.org_header1.setObjectName("org_header1")
        self.label_from = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_from.setGeometry(QtCore.QRect(30, 60, 151, 41))
        self.label_from.setStyleSheet("#label_from {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_from.setObjectName("label_from")
        self.close_btn = QtWidgets.QToolButton(parent=self.msg_widget)
        self.close_btn.setGeometry(QtCore.QRect(520, 10, 31, 31))
        self.close_btn.setObjectName("close_btn")
        self.label_to = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_to.setGeometry(QtCore.QRect(30, 100, 141, 31))
        self.label_to.setStyleSheet("#label_to {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_to.setObjectName("label_to")
        self.label_priority = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_priority.setGeometry(QtCore.QRect(30, 180, 151, 41))
        self.label_priority.setStyleSheet("#label_priority {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_priority.setObjectName("label_priority")
        self.label_status = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_status.setGeometry(QtCore.QRect(30, 220, 151, 41))
        self.label_status.setStyleSheet("#label_status{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        self.btn_cancel = QtWidgets.QPushButton(parent=self.msg_widget)
        self.btn_cancel.setGeometry(QtCore.QRect(380, 680, 81, 31))
        self.btn_cancel.setStyleSheet("#btn_cancel {\n"
"    \n"
"    color: #c62828;              /* Red text color */\n"
"    border: 1.3px solid;\n"
"    border-radius: 8px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_cancel:hover {\n"
"    background-color: #c62828;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_cancel:pressed {\n"
"    background-color: #8e1c1c;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.btn_ok = QtWidgets.QPushButton(parent=self.msg_widget)
        self.btn_ok.setGeometry(QtCore.QRect(470, 680, 81, 31))
        self.btn_ok.setStyleSheet("#btn_ok {\n"
"    background-color: #ffffff;   /* Button base color */\n"
"    color: #006420;              /* Text color */\n"
"    border: 1.3px solid;   /* Border color */\n"
"    border-radius: 8px;          /* Rounded corners */\n"
"    padding: 6px 20px;           /* Comfortable padding */\n"
"    font-family: Segoe UI;   /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_ok:hover {\n"
"    background-color: #006420;  /* Hover background */\n"
"    color: #ffffff;             /* Text color on hover */\n"
"}\n"
"\n"
"#btn_ok:pressed {\n"
"    background-color: #004d18;  /* Darker shade when pressed */\n"
"    border-color: #004d18;\n"
"}\n"
"")
        self.btn_ok.setObjectName("btn_ok")
        self.label_subject = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_subject.setGeometry(QtCore.QRect(30, 140, 141, 31))
        self.label_subject.setStyleSheet("#label_subject{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_subject.setObjectName("label_subject")
        self.label_date = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_date.setGeometry(QtCore.QRect(30, 260, 151, 41))
        self.label_date.setStyleSheet("#label_date{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;       /* Slightly smaller than header1 */\n"
"    font-weight: 500;      /* Medium weight for H2 */\n"
"    color: #000000;        /* Matching your header1 color */\n"
"    letter-spacing: 0.5px; /* Subtle spacing for modern look */\n"
"}\n"
"")
        self.label_date.setObjectName("label_date")
        self.label_message = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_message.setGeometry(QtCore.QRect(30, 300, 301, 41))
        self.label_message.setStyleSheet("#label_message {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight:bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_message.setObjectName("label_message")
        self.text_edit_reply = QtWidgets.QPlainTextEdit(parent=self.msg_widget)
        self.text_edit_reply.setGeometry(QtCore.QRect(30, 520, 521, 151))
        self.text_edit_reply.setStyleSheet("#text_edit_reply {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#text_edit_reply:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#text_edit_reply:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.text_edit_reply.setObjectName("text_edit_reply")
        self.label_reply = QtWidgets.QLabel(parent=self.msg_widget)
        self.label_reply.setGeometry(QtCore.QRect(30, 480, 301, 41))
        self.label_reply.setStyleSheet("#label_reply{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight:bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_reply.setObjectName("label_reply")
        self.line = QtWidgets.QFrame(parent=self.msg_widget)
        self.line.setGeometry(QtCore.QRect(120, 80, 421, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(parent=self.msg_widget)
        self.line_2.setGeometry(QtCore.QRect(120, 120, 421, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(parent=self.msg_widget)
        self.line_3.setGeometry(QtCore.QRect(120, 160, 421, 16))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.line_4 = QtWidgets.QFrame(parent=self.msg_widget)
        self.line_4.setGeometry(QtCore.QRect(120, 200, 421, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(parent=self.msg_widget)
        self.line_5.setGeometry(QtCore.QRect(120, 240, 421, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.line_6 = QtWidgets.QFrame(parent=self.msg_widget)
        self.line_6.setGeometry(QtCore.QRect(120, 280, 421, 16))
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.close_btn_2 = QtWidgets.QToolButton(parent=self.msg_widget)
        self.close_btn_2.setGeometry(QtCore.QRect(330, 680, 31, 31))
        self.close_btn_2.setObjectName("close_btn_2")
        self.close_btn_3 = QtWidgets.QToolButton(parent=self.msg_widget)
        self.close_btn_3.setGeometry(QtCore.QRect(290, 680, 31, 31))
        self.close_btn_3.setObjectName("close_btn_3")
        self.msg_frame = QtWidgets.QFrame(parent=self.msg_widget)
        self.msg_frame.setGeometry(QtCore.QRect(30, 340, 521, 141))
        self.msg_frame.setStyleSheet("#msg_frame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 10px 12px;        /* Comfortable inner spacing for messages */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#msg_frame:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#msg_frame:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.msg_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.msg_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.msg_frame.setObjectName("msg_frame")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.org_header1.setText(_translate("Form", "Message Details"))
        self.label_from.setText(_translate("Form", "From:"))
        self.close_btn.setText(_translate("Form", "x"))
        self.label_to.setText(_translate("Form", "To:"))
        self.label_priority.setText(_translate("Form", "Priority "))
        self.label_status.setText(_translate("Form", "Status:"))
        self.btn_cancel.setText(_translate("Form", "CANCEL"))
        self.btn_ok.setText(_translate("Form", "REPLY"))
        self.label_subject.setText(_translate("Form", "Subject"))
        self.label_date.setText(_translate("Form", "Date:"))
        self.label_message.setText(_translate("Form", "Message :"))
        self.label_reply.setText(_translate("Form", "Reply"))
        self.close_btn_2.setText(_translate("Form", "file"))
        self.close_btn_3.setText(_translate("Form", "fwd"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
