# Form implementation generated from reading ui file 'org_card.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(881, 569)
        self.frame_container = QtWidgets.QFrame(parent=Form)
        self.frame_container.setGeometry(QtCore.QRect(0, 190, 881, 161))
        self.frame_container.setStyleSheet("QFrame#frame_container {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.frame_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_container.setObjectName("frame_container")
        self.line_9 = QtWidgets.QFrame(parent=self.frame_container)
        self.line_9.setGeometry(QtCore.QRect(0, 150, 881, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_recipient = QtWidgets.QLabel(parent=self.frame_container)
        self.label_recipient.setGeometry(QtCore.QRect(30, 10, 92, 21))
        self.label_recipient.setStyleSheet("#label_recipient {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_recipient.setObjectName("label_recipient")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame_container)
        self.layoutWidget.setGeometry(QtCore.QRect(820, 20, 46, 81))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_day = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_day.setStyleSheet("#label_day{\n"
"    color: gray;\n"
"    font-size: 10px;\n"
"}")
        self.label_day.setObjectName("label_day")
        self.verticalLayout.addWidget(self.label_day)
        self.label_stat1 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_stat1.setStyleSheet("#label_stat1{\n"
"    color: gray;\n"
"    font-size: 10px;\n"
"}")
        self.label_stat1.setObjectName("label_stat1")
        self.verticalLayout.addWidget(self.label_stat1)
        self.label_crit = QtWidgets.QLabel(parent=self.frame_container)
        self.label_crit.setGeometry(QtCore.QRect(190, 10, 51, 21))
        self.label_crit.setStyleSheet("#label_crit {\n"
"    background-color: red;\n"
"    color: white;\n"
"    font-weight: bold;\n"
"    text-align:center;\n"
"    border-radius: 10px;  /* Add border-radius for rounded corners */\n"
"    border: 1px solid;  /* Optional: Add border color to make the rounded effect stand out */\n"
"}\n"
"")
        self.label_crit.setObjectName("label_crit")
        self.label_status = QtWidgets.QLabel(parent=self.frame_container)
        self.label_status.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.label_status.setStyleSheet("#label_status {\n"
"    background-color: yellow;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    text-align:center;\n"
"    border-radius: 10px;  /* Add border-radius for rounded corners */\n"
"    border: 1px solid #FFCC00;  /* Optional: Add border color to make the rounded effect stand out */\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        self.label_body_2 = QtWidgets.QLabel(parent=self.frame_container)
        self.label_body_2.setGeometry(QtCore.QRect(150, 40, 151, 16))
        self.label_body_2.setObjectName("label_body_2")
        self.label_body_3 = QtWidgets.QLabel(parent=self.frame_container)
        self.label_body_3.setGeometry(QtCore.QRect(30, 40, 131, 16))
        self.label_body_3.setObjectName("label_body_3")
        self.layoutWidget1 = QtWidgets.QWidget(parent=self.frame_container)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 70, 361, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_subject = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_subject.setObjectName("label_subject")
        self.verticalLayout_2.addWidget(self.label_subject)
        self.label_body = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.label_body.setObjectName("label_body")
        self.verticalLayout_2.addWidget(self.label_body)
        self.label_body_4 = QtWidgets.QLabel(parent=self.frame_container)
        self.label_body_4.setGeometry(QtCore.QRect(310, 40, 151, 16))
        self.label_body_4.setObjectName("label_body_4")
        self.btn_reply = QtWidgets.QPushButton(parent=self.frame_container)
        self.btn_reply.setGeometry(QtCore.QRect(140, 130, 81, 21))
        self.btn_reply.setStyleSheet("#btn_reply {\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_reply:hover {\n"
"    background-color: #006420;  \n"
"    color: #ffffff;             \n"
"}\n"
"\n"
"#btn_reply:pressed {\n"
"    background-color: #004d18;  \n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_reply.setObjectName("btn_reply")
        self.btn_dets = QtWidgets.QPushButton(parent=self.frame_container)
        self.btn_dets.setGeometry(QtCore.QRect(30, 130, 101, 21))
        self.btn_dets.setStyleSheet("#btn_dets {\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_dets:hover {\n"
"    background-color: #006420;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_dets:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_dets.setObjectName("btn_dets")
        self.btn_del = QtWidgets.QPushButton(parent=self.frame_container)
        self.btn_del.setGeometry(QtCore.QRect(230, 130, 81, 21))
        self.btn_del.setStyleSheet("#btn_del {\n"
"    color: #c62828;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_del:hover {\n"
"    background-color: #FF5C00;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_del:pressed {\n"
"    background-color: #8e1c1c;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_del.setObjectName("btn_del")
        self.line_10 = QtWidgets.QFrame(parent=Form)
        self.line_10.setGeometry(QtCore.QRect(0, 180, 881, 20))
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.layoutWidget2 = QtWidgets.QWidget(parent=Form)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_recipient.setText(_translate("Form", "Andre Louie"))
        self.label_day.setText(_translate("Form", "1d Ago"))
        self.label_stat1.setText(_translate("Form", "Pending"))
        self.label_crit.setText(_translate("Form", "Critical"))
        self.label_status.setText(_translate("Form", "Pending"))
        self.label_body_2.setText(_translate("Form", "To:sample123@cmu.edu.ph"))
        self.label_body_3.setText(_translate("Form", "From: IT Department"))
        self.label_subject.setText(_translate("Form", "sample subject"))
        self.label_body.setText(_translate("Form", "sample body "))
        self.label_body_4.setText(_translate("Form", "11/02/2025"))
        self.btn_reply.setText(_translate("Form", "REPLY"))
        self.btn_dets.setText(_translate("Form", "VIEW DETAILS"))
        self.btn_del.setText(_translate("Form", "DELETE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
