# Generated by Django 5.2.5 on 2025-11-29 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('canceled', 'Canceled'), ('completed', 'Completed'), ('denied', 'Denied')], default='pending', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.facultyprofile')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='users.studentprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['faculty', 'status'], name='Appointment_faculty_40b3a8_idx'), models.Index(fields=['student'], name='Appointment_student_88a50c_idx'), models.Index(fields=['start_at'], name='Appointment_start_a_916d81_idx'), models.Index(fields=['end_at'], name='Appointment_end_at_8d2692_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('end_at__gt', models.F('start_at'))), name='slot_end_after_start')],
            },
        ),
        migrations.CreateModel(
            name='AvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('MON', 'Monday'), ('TUE', 'Tuesday'), ('WED', 'Wednesday'), ('THU', 'Thursday'), ('FRI', 'Friday'), ('SAT', 'Saturday'), ('SUN', 'Sunday')], max_length=3)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='users.facultyprofile')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='valid_time_span', to='Academics.semester')),
            ],
            options={
                'indexes': [models.Index(fields=['faculty', 'day_of_week'], name='Appointment_faculty_25deb7_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusyBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('source_id', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=150)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='busy_blocks', to='users.facultyprofile')),
                ('source_ct', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['faculty', 'start_at'], name='Appointment_faculty_dc554e_idx'), models.Index(fields=['start_at', 'end_at'], name='Appointment_start_a_2da969_idx')],
            },
        ),
    ]
