# Generated by Django 5.2.5 on 2025-12-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appointments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrule',
            name='semester',
            field=models.IntegerField(),
        ),
    ]
