# Form implementation generated from reading ui file 'frontend/ui/Classroom/classroom_classworks_content.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClassroomClassworksContent(object):
    def setupUi(self, ClassroomClassworksContent):
        ClassroomClassworksContent.setObjectName("ClassroomClassworksContent")
        ClassroomClassworksContent.resize(940, 530)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ClassroomClassworksContent.sizePolicy().hasHeightForWidth())
        ClassroomClassworksContent.setSizePolicy(sizePolicy)
        ClassroomClassworksContent.setMinimumSize(QtCore.QSize(400, 530))
        ClassroomClassworksContent.setStyleSheet("QWidget {\n"
"       background-color: transparent;\n"
"       font-family: \"Poppins\", Arial, sans-serif;\n"
"   }")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ClassroomClassworksContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.classworkMainVerticalLayout = QtWidgets.QVBoxLayout()
        self.classworkMainVerticalLayout.setContentsMargins(20, 20, 20, 20)
        self.classworkMainVerticalLayout.setSpacing(15)
        self.classworkMainVerticalLayout.setObjectName("classworkMainVerticalLayout")
        self.topBarLayout = QtWidgets.QHBoxLayout()
        self.topBarLayout.setSpacing(15)
        self.topBarLayout.setObjectName("topBarLayout")
        self.createButton = QtWidgets.QToolButton(parent=ClassroomClassworksContent)
        self.createButton.setMaximumSize(QtCore.QSize(100, 40))
        self.createButton.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.NoContextMenu)
        self.createButton.setStyleSheet("   QToolButton {\n"
"       background-color: #084924;\n"
"       color: white;\n"
"       border: none;\n"
"       padding: 6px 12px;\n"
"       border-radius: 5px;\n"
"       font-weight: 600;\n"
"       font-size: 11px;\n"
"   }\n"
"   QToolButton:hover {\n"
"       background-color: #1B5E20;\n"
"   }\n"
"   QToolButton:pressed {\n"
"       background-color: #0D4E12;\n"
"   }")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/baseline-add.svg"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.createButton.setIcon(icon)
        self.createButton.setPopupMode(QtWidgets.QToolButton.ToolButtonPopupMode.MenuButtonPopup)
        self.createButton.setToolButtonStyle(QtCore.Qt.ToolButtonStyle.ToolButtonTextBesideIcon)
        self.createButton.setArrowType(QtCore.Qt.ArrowType.NoArrow)
        self.createButton.setObjectName("createButton")
        self.topBarLayout.addWidget(self.createButton)
        spacerItem = QtWidgets.QSpacerItem(60, 20, QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.topBarLayout.addItem(spacerItem)
        self.classworkMainVerticalLayout.addLayout(self.topBarLayout)
        self.filterComboBox = QtWidgets.QComboBox(parent=ClassroomClassworksContent)
        self.filterComboBox.setMaximumSize(QtCore.QSize(276, 40))
        self.filterComboBox.setStyleSheet("QComboBox {\n"
"       border: 1px solid #D0D7DE;\n"
"       border-radius: 4px;\n"
"       padding: 5px 8px;\n"
"       background-color: white;\n"
"       font-size: 12px;\n"
"   }\n"
"   QComboBox:hover {\n"
"       border-color: #A8A8A8;\n"
"   }\n"
"   QComboBox::drop-down {\n"
"       border: none;\n"
"       width: 20px;\n"
"   }\n"
"\n"
"    QComboBox::down-arrow {\n"
"       image: none;\n"
"       border-left: 4px solid transparent;\n"
"       border-right: 4px solid transparent;\n"
"       border-top: 4px solid #666;\n"
"   }\n"
"\n"
"")
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.classworkMainVerticalLayout.addWidget(self.filterComboBox)
        self.topicScrollArea = QtWidgets.QScrollArea(parent=ClassroomClassworksContent)
        self.topicScrollArea.setMinimumSize(QtCore.QSize(200, 0))
        self.topicScrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.topicScrollArea.setBaseSize(QtCore.QSize(0, 0))
        self.topicScrollArea.setStyleSheet("QScrollArea {\n"
"       border: none;\n"
"       background-color: transparent;\n"
"   }\n"
"   QScrollBar:vertical {\n"
"       border: none;\n"
"       background: #F1F1F1;\n"
"       width: 8px;\n"
"       border-radius: 4px;\n"
"   }\n"
"   QScrollBar::handle:vertical {\n"
"       background: #C1C1C1;\n"
"       border-radius: 4px;\n"
"       min-height: 20px;\n"
"   }")
        self.topicScrollArea.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topicScrollArea.setWidgetResizable(True)
        self.topicScrollArea.setObjectName("topicScrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 882, 370))
        self.scrollAreaWidgetContents.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topicListLayout = QtWidgets.QVBoxLayout()
        self.topicListLayout.setContentsMargins(-1, 9, 0, 0)
        self.topicListLayout.setSpacing(4)
        self.topicListLayout.setObjectName("topicListLayout")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.topicListLayout.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.topicListLayout)
        self.topicScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.classworkMainVerticalLayout.addWidget(self.topicScrollArea)
        self.verticalLayout_2.addLayout(self.classworkMainVerticalLayout)

        self.retranslateUi(ClassroomClassworksContent)
        QtCore.QMetaObject.connectSlotsByName(ClassroomClassworksContent)

    def retranslateUi(self, ClassroomClassworksContent):
        _translate = QtCore.QCoreApplication.translate
        ClassroomClassworksContent.setWindowTitle(_translate("ClassroomClassworksContent", "classworks"))
        self.createButton.setText(_translate("ClassroomClassworksContent", "Create"))
        self.filterComboBox.setItemText(0, _translate("ClassroomClassworksContent", "All items"))
        self.filterComboBox.setItemText(1, _translate("ClassroomClassworksContent", "Material"))
        self.filterComboBox.setItemText(2, _translate("ClassroomClassworksContent", "Assessment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClassroomClassworksContent = QtWidgets.QWidget()
    ui = Ui_ClassroomClassworksContent()
    ui.setupUi(ClassroomClassworksContent)
    ClassroomClassworksContent.show()
    sys.exit(app.exec())
