# Form implementation generated from reading ui file 'frontend\ui\Classroom\stream_post.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClassroomStreamContent(object):
    def setupUi(self, ClassroomStreamContent):
        ClassroomStreamContent.setObjectName("ClassroomStreamContent")
        ClassroomStreamContent.resize(934, 513)
        ClassroomStreamContent.setStyleSheet("QWidget {\n"
"    background-color: transparent;\n"
"    font-family:\"Poppins\";\n"
"}")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ClassroomStreamContent)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_layout = QtWidgets.QVBoxLayout()
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.mainContent = QtWidgets.QWidget(parent=ClassroomStreamContent)
        self.mainContent.setMinimumSize(QtCore.QSize(200, 0))
        self.mainContent.setStyleSheet("QWidget {\n"
"    background: transparent;\n"
"    border-radius: 12px;\n"
"}")
        self.mainContent.setObjectName("mainContent")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainContent)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainContent)
        self.scrollArea.setMinimumSize(QtCore.QSize(200, 0))
        self.scrollArea.setStyleSheet("QScrollArea {\n"
"       border: none;\n"
"       background-color: transparent;\n"
"   }\n"
"   QScrollBar:vertical {\n"
"       border: none;\n"
"       background: #F1F1F1;\n"
"       width: 8px;\n"
"       border-radius: 4px;\n"
"   }\n"
"   QScrollBar::handle:vertical {\n"
"       background: #C1C1C1;\n"
"       border-radius: 4px;\n"
"       min-height: 20px;\n"
"   }\n"
"QScrollBar:horizontal {\n"
"       border: none;\n"
"       background: #F1F1F1;\n"
"       width: 8px;\n"
"       border-radius: 4px;\n"
"   }\n"
"   QScrollBar::handle:horizontal {\n"
"       background: #C1C1C1;\n"
"       border-radius: 4px;\n"
"       min-height: 20px;\n"
"   }")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 888, 548))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.courseHeDER = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.courseHeDER.sizePolicy().hasHeightForWidth())
        self.courseHeDER.setSizePolicy(sizePolicy)
        self.courseHeDER.setMinimumSize(QtCore.QSize(200, 200))
        self.courseHeDER.setStyleSheet("QWidget {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, \n"
"        stop:0 #2d8f6f, stop:1 #4db38b);\n"
"    border-radius: 12px;\n"
"}")
        self.courseHeDER.setObjectName("courseHeDER")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.courseHeDER)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.headerLayout_2 = QtWidgets.QVBoxLayout()
        self.headerLayout_2.setContentsMargins(40, 30, 40, 30)
        self.headerLayout_2.setObjectName("headerLayout_2")
        self.courseCode_label = QtWidgets.QLabel(parent=self.courseHeDER)
        self.courseCode_label.setStyleSheet("QLabel {\n"
"    color: rgba(255, 255, 255, 0.8);\n"
"    font-size: 14px;\n"
"    font-family: \"Poppins\";\n"
"    background: transparent;\n"
"}")
        self.courseCode_label.setObjectName("courseCode_label")
        self.headerLayout_2.addWidget(self.courseCode_label)
        self.courseTitle_label = QtWidgets.QLabel(parent=self.courseHeDER)
        self.courseTitle_label.setStyleSheet("QLabel {\n"
"    color: white;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    font-family: \"Poppins-Semi-Bold\";\n"
"    background: transparent;\n"
"}")
        self.courseTitle_label.setWordWrap(True)
        self.courseTitle_label.setObjectName("courseTitle_label")
        self.headerLayout_2.addWidget(self.courseTitle_label)
        self.courseSection_label = QtWidgets.QLabel(parent=self.courseHeDER)
        self.courseSection_label.setStyleSheet("QLabel {\n"
"    color: rgba(255, 255, 255, 0.9);\n"
"    font-size: 16px;\n"
"    font-weight: 400;\n"
"    font-family: \"Poppins\";\n"
"    background: transparent;\n"
"    margin-top: 8px;\n"
"}")
        self.courseSection_label.setObjectName("courseSection_label")
        self.headerLayout_2.addWidget(self.courseSection_label)
        self.verticalLayout_4.addLayout(self.headerLayout_2)
        self.verticalLayout_5.addWidget(self.courseHeDER)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 8, 0, 30)
        self.horizontalLayout_5.setSpacing(20)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.syllabusFrame = QtWidgets.QFrame(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.syllabusFrame.sizePolicy().hasHeightForWidth())
        self.syllabusFrame.setSizePolicy(sizePolicy)
        self.syllabusFrame.setMinimumSize(QtCore.QSize(133, 152))
        self.syllabusFrame.setMaximumSize(QtCore.QSize(140, 170))
        self.syllabusFrame.setStyleSheet("QFrame {\n"
"                background-color: white;\n"
"                border: 1px solid #E0E0E0;\n"
"                border-radius: 20px;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #F8F9FA;\n"
"                border-color: #D0D7DE;\n"
"}")
        self.syllabusFrame.setObjectName("syllabusFrame")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.syllabusFrame)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.syllabusCard_layout = QtWidgets.QVBoxLayout()
        self.syllabusCard_layout.setSpacing(7)
        self.syllabusCard_layout.setObjectName("syllabusCard_layout")
        self.syllabussss = QtWidgets.QWidget(parent=self.syllabusFrame)
        self.syllabussss.setObjectName("syllabussss")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.syllabussss)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.icon_label2 = QtWidgets.QLabel(parent=self.syllabussss)
        self.icon_label2.setMaximumSize(QtCore.QSize(28, 28))
        self.icon_label2.setStyleSheet("QLabel {\n"
"    background-color: #084924;\n"
"    border-radius: 20px;\n"
"    border: 2px solid white;\n"
"    color: white;\n"
"    font-size: 18px;\n"
"}")
        self.icon_label2.setText("")
        self.icon_label2.setWordWrap(False)
        self.icon_label2.setObjectName("icon_label2")
        self.horizontalLayout_7.addWidget(self.icon_label2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(parent=self.syllabussss)
        self.label_2.setStyleSheet("border: none;\n"
"font-size: 16px;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_6)
        self.syllabusCard_layout.addWidget(self.syllabussss)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.syllabusCard_layout.addItem(spacerItem)
        self.pushButton = QtWidgets.QPushButton(parent=self.syllabusFrame)
        self.pushButton.setObjectName("pushButton")
        self.syllabusCard_layout.addWidget(self.pushButton)
        self.verticalLayout_9.addLayout(self.syllabusCard_layout)
        self.horizontalLayout_5.addWidget(self.syllabusFrame, 0, QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignTop)
        self.stream_item_container = QtWidgets.QWidget(parent=self.scrollAreaWidgetContents)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stream_item_container.sizePolicy().hasHeightForWidth())
        self.stream_item_container.setSizePolicy(sizePolicy)
        self.stream_item_container.setObjectName("stream_item_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.stream_item_container)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.stream_items_layout = QtWidgets.QVBoxLayout()
        self.stream_items_layout.setSpacing(10)
        self.stream_items_layout.setObjectName("stream_items_layout")
        self.postTemplate = QtWidgets.QFrame(parent=self.stream_item_container)
        self.postTemplate.setMinimumSize(QtCore.QSize(200, 0))
        self.postTemplate.setStyleSheet("QFrame {\n"
"                background-color: white;\n"
"                border: 1px solid #E0E0E0;\n"
"                border-radius: 20px;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #F8F9FA;\n"
"                border-color: #D0D7DE;\n"
"}")
        self.postTemplate.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.postTemplate.setObjectName("postTemplate")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.postTemplate)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.icon_label = QtWidgets.QLabel(parent=self.postTemplate)
        self.icon_label.setMaximumSize(QtCore.QSize(50, 50))
        self.icon_label.setStyleSheet("background-color: #084924; \n"
"border-radius: 25px; \n"
"border: 2px solid white;")
        self.icon_label.setObjectName("icon_label")
        self.horizontalLayout_2.addWidget(self.icon_label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.title_label = QtWidgets.QLabel(parent=self.postTemplate)
        self.title_label.setStyleSheet("font-size: 18px;\n"
"border:none;\n"
"\n"
"QFrame {\n"
"                background-color: white;\n"
"                border: 1px solid #E0E0E0;\n"
"                border-radius: 20px;\n"
"            }\n"
"QFrame:hover {\n"
"                background-color: #F8F9FA;\n"
"                border-color: #D0D7DE;\n"
"}")
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.verticalLayout_3.addWidget(self.title_label)
        self.date_label = QtWidgets.QLabel(parent=self.postTemplate)
        self.date_label.setStyleSheet("\n"
"    font-size: 14px;\n"
"    border:none;")
        self.date_label.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.date_label.setWordWrap(True)
        self.date_label.setObjectName("date_label")
        self.verticalLayout_3.addWidget(self.date_label)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.menu_button = QtWidgets.QPushButton(parent=self.postTemplate)
        self.menu_button.setMaximumSize(QtCore.QSize(32, 32))
        self.menu_button.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #6c757d;\n"
"    font-size: 32px;\n"
"    font-weight: bold;\n"
"    border-radius: 16px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #495057;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #e9ecef;\n"
"}")
        self.menu_button.setObjectName("menu_button")
        self.horizontalLayout_2.addWidget(self.menu_button)
        self.stream_items_layout.addWidget(self.postTemplate)
        self.verticalLayout_6.addLayout(self.stream_items_layout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_6.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.stream_item_container)
        self.verticalLayout_5.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_5.addItem(spacerItem2)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.main_layout.addWidget(self.mainContent)
        self.verticalLayout_2.addLayout(self.main_layout)

        self.retranslateUi(ClassroomStreamContent)
        QtCore.QMetaObject.connectSlotsByName(ClassroomStreamContent)

    def retranslateUi(self, ClassroomStreamContent):
        _translate = QtCore.QCoreApplication.translate
        ClassroomStreamContent.setWindowTitle(_translate("ClassroomStreamContent", "Form"))
        self.courseCode_label.setText(_translate("ClassroomStreamContent", "ITSD81"))
        self.courseTitle_label.setText(_translate("ClassroomStreamContent", "DESKTOP APPLICATION DEVELOPMENT LECTURE"))
        self.courseSection_label.setText(_translate("ClassroomStreamContent", "BSIT-2C\n"
"MONDAY - 1:00 - 4:00 PM"))
        self.label_2.setText(_translate("ClassroomStreamContent", "Syllabus"))
        self.pushButton.setText(_translate("ClassroomStreamContent", "View"))
        self.icon_label.setText(_translate("ClassroomStreamContent", "TextLabel"))
        self.title_label.setText(_translate("ClassroomStreamContent", "Carlos Fidel Castro posted a material: Desktop Project Guidelines"))
        self.date_label.setText(_translate("ClassroomStreamContent", "Aug 18"))
        self.menu_button.setText(_translate("ClassroomStreamContent", "⋮"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ClassroomStreamContent = QtWidgets.QWidget()
    ui = Ui_ClassroomStreamContent()
    ui.setupUi(ClassroomStreamContent)
    ClassroomStreamContent.show()
    sys.exit(app.exec())
