# Form implementation generated from reading ui file 'frontend/ui/Classroom/view_material.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_viewMaterial(object):
    def setupUi(self, viewMaterial):
        viewMaterial.setObjectName("viewMaterial")
        viewMaterial.resize(747, 452)
        viewMaterial.setMinimumSize(QtCore.QSize(200, 300))
        viewMaterial.setStyleSheet("QWidget { background-color: white; font-family: \"Poppins\", Arial, sans-serif; }")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(viewMaterial)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.headerLayout = QtWidgets.QHBoxLayout()
        self.headerLayout.setContentsMargins(-1, 10, -1, -1)
        self.headerLayout.setObjectName("headerLayout")
        self.backButton = QtWidgets.QLabel(parent=viewMaterial)
        self.backButton.setMinimumSize(QtCore.QSize(50, 50))
        self.backButton.setMaximumSize(QtCore.QSize(50, 50))
        self.backButton.setStyleSheet("border: none; background: transparent; padding: 5px;")
        self.backButton.setText("")
        self.backButton.setPixmap(QtGui.QPixmap(":/icons/back2.png"))
        self.backButton.setObjectName("backButton")
        self.headerLayout.addWidget(self.backButton)
        self.titleMetaLayout = QtWidgets.QVBoxLayout()
        self.titleMetaLayout.setObjectName("titleMetaLayout")
        self.title_label = QtWidgets.QLabel(parent=viewMaterial)
        self.title_label.setStyleSheet("font-size: 54px; font-weight: 400; color: #333; margin-bottom: 10px;\n"
"")
        self.title_label.setWordWrap(True)
        self.title_label.setObjectName("title_label")
        self.titleMetaLayout.addWidget(self.title_label)
        self.metaLayout = QtWidgets.QHBoxLayout()
        self.metaLayout.setObjectName("metaLayout")
        self.instructor_label = QtWidgets.QLabel(parent=viewMaterial)
        self.instructor_label.setStyleSheet("font-size: 20px; color: #24292f;\n"
"margin-left: 10px;")
        self.instructor_label.setObjectName("instructor_label")
        self.metaLayout.addWidget(self.instructor_label)
        self.date_label = QtWidgets.QLabel(parent=viewMaterial)
        self.date_label.setStyleSheet("font-size: 20px; color: #656d76; padding-left: 5px;")
        self.date_label.setObjectName("date_label")
        self.metaLayout.addWidget(self.date_label)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.metaLayout.addItem(spacerItem)
        self.titleMetaLayout.addLayout(self.metaLayout)
        self.headerLayout.addLayout(self.titleMetaLayout)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.headerLayout.addItem(spacerItem1)
        self.menuButton = QtWidgets.QPushButton(parent=viewMaterial)
        self.menuButton.setMaximumSize(QtCore.QSize(40, 40))
        self.menuButton.setStyleSheet("QPushButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    color: #6c757d;\n"
"    font-size: 40px;\n"
"    font-weight: bold;\n"
"    border-radius: 20px;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #f8f9fa;\n"
"    color: #495057;\n"
"}\n"
"QPushButton:pressed {\n"
"    background-color: #e9ecef;\n"
"}")
        self.menuButton.setObjectName("menuButton")
        self.headerLayout.addWidget(self.menuButton)
        self.verticalLayout.addLayout(self.headerLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.descriptionEdit = QtWidgets.QTextEdit(parent=viewMaterial)
        self.descriptionEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.descriptionEdit.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.descriptionEdit.setStyleSheet("font-size: 16px; color: #000000; padding: 10px;  border: 1px solid #ddd; border-radius: 5px;\n"
"margin-left: 80px;\n"
"margin-bottom: 10px;")
        self.descriptionEdit.setLineWrapMode(QtWidgets.QTextEdit.LineWrapMode.WidgetWidth)
        self.descriptionEdit.setLineWrapColumnOrWidth(0)
        self.descriptionEdit.setReadOnly(True)
        self.descriptionEdit.setTextInteractionFlags(QtCore.Qt.TextInteractionFlag.TextSelectableByMouse)
        self.descriptionEdit.setObjectName("descriptionEdit")
        self.verticalLayout_2.addWidget(self.descriptionEdit)
        self.attachementLayout = QtWidgets.QHBoxLayout()
        self.attachementLayout.setContentsMargins(80, 10, -1, 10)
        self.attachementLayout.setSpacing(10)
        self.attachementLayout.setObjectName("attachementLayout")
        self.attachmentFrame = QtWidgets.QFrame(parent=viewMaterial)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.attachmentFrame.sizePolicy().hasHeightForWidth())
        self.attachmentFrame.setSizePolicy(sizePolicy)
        self.attachmentFrame.setMinimumSize(QtCore.QSize(300, 76))
        self.attachmentFrame.setMaximumSize(QtCore.QSize(400, 76))
        self.attachmentFrame.setMouseTracking(True)
        self.attachmentFrame.setStyleSheet("QFrame #attachmentFrame { \n"
"background-color: white; \n"
"border: 1px solid #ddd; \n"
"border-radius: 10px; \n"
"padding: 5px;}")
        self.attachmentFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.attachmentFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.attachmentFrame.setObjectName("attachmentFrame")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.attachmentFrame)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.attachmentInnerLayout = QtWidgets.QVBoxLayout()
        self.attachmentInnerLayout.setObjectName("attachmentInnerLayout")
        self.attachmentName = QtWidgets.QLabel(parent=self.attachmentFrame)
        self.attachmentName.setStyleSheet("\n"
"font-size: 16px; \n"
"color: #24292f; \n"
"text-align: center; \n"
"text-decoration: underline;\n"
"")
        self.attachmentName.setObjectName("attachmentName")
        self.attachmentInnerLayout.addWidget(self.attachmentName)
        self.attachmentType = QtWidgets.QLabel(parent=self.attachmentFrame)
        self.attachmentType.setStyleSheet("font-size: 14px; color: #656d76; text-align: center;")
        self.attachmentType.setObjectName("attachmentType")
        self.attachmentInnerLayout.addWidget(self.attachmentType)
        self.verticalLayout_7.addLayout(self.attachmentInnerLayout)
        self.attachementLayout.addWidget(self.attachmentFrame)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.attachementLayout.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.attachementLayout)
        self.commentLayout = QtWidgets.QHBoxLayout()
        self.commentLayout.setObjectName("commentLayout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.commentLayout.addItem(spacerItem3)
        self.label = QtWidgets.QLabel(parent=viewMaterial)
        self.label.setMaximumSize(QtCore.QSize(38, 38))
        self.label.setStyleSheet("background-color: #084924; border-radius: 19px; color: white; min-width: 38px; min-height: 38px; text-align: center; line-height: 38px;")
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.commentLayout.addWidget(self.label)
        self.commentBox = QtWidgets.QTextEdit(parent=viewMaterial)
        self.commentBox.setMinimumSize(QtCore.QSize(200, 20))
        self.commentBox.setMaximumSize(QtCore.QSize(16777215, 50))
        self.commentBox.setStyleSheet("font-size: 14px; color: #24292f; padding: 5px; border: 1px solid #ddd; border-radius: 16.5px;")
        self.commentBox.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOff)
        self.commentBox.setObjectName("commentBox")
        self.commentLayout.addWidget(self.commentBox)
        self.pushButton = QtWidgets.QPushButton(parent=viewMaterial)
        self.pushButton.setObjectName("pushButton")
        self.commentLayout.addWidget(self.pushButton)
        self.verticalLayout_2.addLayout(self.commentLayout)
        spacerItem4 = QtWidgets.QSpacerItem(20, 60, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem4)

        self.retranslateUi(viewMaterial)
        QtCore.QMetaObject.connectSlotsByName(viewMaterial)

    def retranslateUi(self, viewMaterial):
        _translate = QtCore.QCoreApplication.translate
        viewMaterial.setWindowTitle(_translate("viewMaterial", "material details"))
        self.title_label.setText(_translate("viewMaterial", "Desktop Project Guidelines"))
        self.instructor_label.setText(_translate("viewMaterial", "Carlos Fidel Castro"))
        self.date_label.setText(_translate("viewMaterial", "• August 18, 2025"))
        self.menuButton.setText(_translate("viewMaterial", "⋮"))
        self.descriptionEdit.setHtml(_translate("viewMaterial", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins,Arial,sans-serif\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14px;\">Please ensure that the task is completed according to the requirements provided, keeping everything consistent and aligned throughout the process. Make sure to follow the necessary steps as outlined, review your work before finalizing, and confirm that it meets the expected standards. Always double-check that the format is correct, the details are accurate, and the output follows the general guidelines. Be mindful of maintaining a clear structure, avoid unnecessary errors, and ensure that the submission is properly prepared before turning it in.</span></p></body></html>"))
        self.attachmentName.setText(_translate("viewMaterial", "Desktop project guidelines"))
        self.attachmentType.setText(_translate("viewMaterial", "PDF"))
        self.label.setText(_translate("viewMaterial", "C"))
        self.commentBox.setHtml(_translate("viewMaterial", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Poppins,Arial,sans-serif\'; font-size:14px; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt;\">Add a comment...</span></p></body></html>"))
        self.pushButton.setText(_translate("viewMaterial", "Send"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    viewMaterial = QtWidgets.QWidget()
    ui = Ui_viewMaterial()
    ui.setupUi(viewMaterial)
    viewMaterial.show()
    sys.exit(app.exec())
