# Generated by Django 5.2.5 on 2025-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='abbr',
            field=models.CharField(default='BSIT', max_length=10, unique=True),
            preserve_default=False,
        ),
    ]
