# Generated by Django 5.2.5 on 2025-09-20 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_organization_orgmembership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orgmembership',
            name='organization',
        ),
        migrations.AlterUniqueTogether(
            name='orgmembership',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orgmembership',
            name='student',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='OrgMembership',
        ),
    ]
