# Form implementation generated from reading ui file 'audit_logs.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import resources_rc

class Ui_audit_logs_widget(object):
    def setupUi(self, audit_logs_widget):
        audit_logs_widget.setObjectName("audit_logs_widget")
        audit_logs_widget.resize(1200, 800)
        self.verticalLayout = QtWidgets.QVBoxLayout(audit_logs_widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.audit_logs_header = QtWidgets.QHBoxLayout()
        self.audit_logs_header.setObjectName("audit_logs_header")
        self.audit_burger_ic = QtWidgets.QPushButton(parent=audit_logs_widget)
        self.audit_burger_ic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.audit_burger_ic.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.audit_burger_ic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/organization/icons/burger_ic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.audit_burger_ic.setIcon(icon)
        self.audit_burger_ic.setIconSize(QtCore.QSize(40, 40))
        self.audit_burger_ic.setObjectName("audit_burger_ic")
        self.audit_logs_header.addWidget(self.audit_burger_ic)
        self.audit_logs_label = QtWidgets.QLabel(parent=audit_logs_widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setKerning(True)
        self.audit_logs_label.setFont(font)
        self.audit_logs_label.setObjectName("audit_logs_label")
        self.audit_logs_header.addWidget(self.audit_logs_label)
        spacerItem = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.audit_logs_header.addItem(spacerItem)
        self.audit_search_container = QtWidgets.QFrame(parent=audit_logs_widget)
        self.audit_search_container.setMaximumSize(QtCore.QSize(16777215, 40))
        self.audit_search_container.setStyleSheet("QFrame {\n"
"    border: 1px solid #084924;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"};")
        self.audit_search_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.audit_search_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.audit_search_container.setObjectName("audit_search_container")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.audit_search_container)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.audit_line_edit = QtWidgets.QLineEdit(parent=self.audit_search_container)
        self.audit_line_edit.setObjectName("audit_line_edit")
        self.horizontalLayout_9.addWidget(self.audit_line_edit)
        self.audit_search_btn = QtWidgets.QToolButton(parent=self.audit_search_container)
        self.audit_search_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/organization/icons/search_ic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.audit_search_btn.setIcon(icon1)
        self.audit_search_btn.setIconSize(QtCore.QSize(30, 30))
        self.audit_search_btn.setObjectName("audit_search_btn")
        self.horizontalLayout_9.addWidget(self.audit_search_btn)
        self.audit_logs_header.addWidget(self.audit_search_container)
        self.audit_back_btn = QtWidgets.QPushButton(parent=audit_logs_widget)
        self.audit_back_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.audit_back_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/organization/icons/Back IC.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.audit_back_btn.setIcon(icon2)
        self.audit_back_btn.setIconSize(QtCore.QSize(30, 30))
        self.audit_back_btn.setObjectName("audit_back_btn")
        self.audit_logs_header.addWidget(self.audit_back_btn)
        self.verticalLayout.addLayout(self.audit_logs_header)
        self.audit_table_container = QtWidgets.QFrame(parent=audit_logs_widget)
        self.audit_table_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.audit_table_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.audit_table_container.setObjectName("audit_table_container")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.audit_table_container)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.table_header = QtWidgets.QWidget(parent=self.audit_table_container)
        self.table_header.setObjectName("table_header")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.table_header)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.table_header_label = QtWidgets.QLabel(parent=self.table_header)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.table_header_label.setFont(font)
        self.table_header_label.setObjectName("table_header_label")
        self.verticalLayout_16.addWidget(self.table_header_label)
        self.adult_hr_line = QtWidgets.QFrame(parent=self.table_header)
        self.adult_hr_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.adult_hr_line.setStyleSheet("QFrame {\n"
"    background-color: black;\n"
"}")
        self.adult_hr_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.adult_hr_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.adult_hr_line.setObjectName("adult_hr_line")
        self.verticalLayout_16.addWidget(self.adult_hr_line)
        self.verticalLayout_17.addWidget(self.table_header)
        self.audit_table_view = QtWidgets.QTableView(parent=self.audit_table_container)
        self.audit_table_view.setStyleSheet("QTableView {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}")
        self.audit_table_view.setObjectName("audit_table_view")
        self.verticalLayout_17.addWidget(self.audit_table_view)
        self.verticalLayout.addWidget(self.audit_table_container)

        self.retranslateUi(audit_logs_widget)
        QtCore.QMetaObject.connectSlotsByName(audit_logs_widget)

    def retranslateUi(self, audit_logs_widget):
        _translate = QtCore.QCoreApplication.translate
        audit_logs_widget.setWindowTitle(_translate("audit_logs_widget", "Form"))
        self.audit_logs_label.setText(_translate("audit_logs_widget", "Audit Logs"))
        self.audit_search_btn.setText(_translate("audit_logs_widget", "..."))
        self.audit_search_btn.setShortcut(_translate("audit_logs_widget", "Return, Enter"))
        self.audit_back_btn.setShortcut(_translate("audit_logs_widget", "Esc"))
        self.table_header_label.setText(_translate("audit_logs_widget", "Organization Actions List"))
