# Form implementation generated from reading ui file 'generate_reports.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import resources_rc

class Ui_generate_reports_widget(object):
    def setupUi(self, generate_reports_widget):
        generate_reports_widget.setObjectName("generate_reports_widget")
        generate_reports_widget.resize(1200, 801)
        generate_reports_widget.setMinimumSize(QtCore.QSize(600, 500))
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(generate_reports_widget)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.generate_reports_header = QtWidgets.QHBoxLayout()
        self.generate_reports_header.setObjectName("generate_reports_header")
        self.burgern_ic = QtWidgets.QPushButton(parent=generate_reports_widget)
        self.burgern_ic.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.burgern_ic.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.burgern_ic.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/organization/icons/burger_ic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.burgern_ic.setIcon(icon)
        self.burgern_ic.setIconSize(QtCore.QSize(40, 40))
        self.burgern_ic.setObjectName("burgern_ic")
        self.generate_reports_header.addWidget(self.burgern_ic)
        self.header_laberl_reports = QtWidgets.QLabel(parent=generate_reports_widget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setKerning(True)
        self.header_laberl_reports.setFont(font)
        self.header_laberl_reports.setObjectName("header_laberl_reports")
        self.generate_reports_header.addWidget(self.header_laberl_reports)
        spacerItem = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.generate_reports_header.addItem(spacerItem)
        self.back_btn_reports = QtWidgets.QPushButton(parent=generate_reports_widget)
        self.back_btn_reports.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.back_btn_reports.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/organization/icons/Back IC.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_btn_reports.setIcon(icon1)
        self.back_btn_reports.setIconSize(QtCore.QSize(30, 30))
        self.back_btn_reports.setObjectName("back_btn_reports")
        self.generate_reports_header.addWidget(self.back_btn_reports)
        self.verticalLayout_4.addLayout(self.generate_reports_header)
        self.main_container = QtWidgets.QFrame(parent=generate_reports_widget)
        self.main_container.setStyleSheet("QFrame {\n"
"}\n"
"\n"
"#main_container {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"};")
        self.main_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_container.setObjectName("main_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.main_container)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.options_laberl = QtWidgets.QLabel(parent=self.main_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.options_laberl.setFont(font)
        self.options_laberl.setObjectName("options_laberl")
        self.verticalLayout_3.addWidget(self.options_laberl)
        self.hr_line = QtWidgets.QFrame(parent=self.main_container)
        self.hr_line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.hr_line.setStyleSheet("QFrame {\n"
"    background-color: black;\n"
"}")
        self.hr_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hr_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hr_line.setObjectName("hr_line")
        self.verticalLayout_3.addWidget(self.hr_line)
        self.options = QtWidgets.QFrame(parent=self.main_container)
        self.options.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.options.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.options.setObjectName("options")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.options)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.dropdown_container = QtWidgets.QWidget(parent=self.options)
        self.dropdown_container.setStyleSheet("QPushButton {\n"
"    padding: 10px;\n"
"};")
        self.dropdown_container.setObjectName("dropdown_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.dropdown_container)
        self.verticalLayout.setObjectName("verticalLayout")
        self.first_row_dropdown = QtWidgets.QWidget(parent=self.dropdown_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.first_row_dropdown.setFont(font)
        self.first_row_dropdown.setStyleSheet("QComboBox {\n"
"    border-radius: 10px;\n"
"    color: white;\n"
"    background-color: #084924;\n"
"    padding: 10px;\n"
"};")
        self.first_row_dropdown.setObjectName("first_row_dropdown")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.first_row_dropdown)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.select_org_dd = QtWidgets.QComboBox(parent=self.first_row_dropdown)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.select_org_dd.setFont(font)
        self.select_org_dd.setObjectName("select_org_dd")
        self.select_org_dd.addItem("")
        self.horizontalLayout.addWidget(self.select_org_dd, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.report_type_dd = QtWidgets.QComboBox(parent=self.first_row_dropdown)
        self.report_type_dd.setObjectName("report_type_dd")
        self.report_type_dd.addItem("")
        self.report_type_dd.addItem("")
        self.report_type_dd.addItem("")
        self.report_type_dd.addItem("")
        self.horizontalLayout.addWidget(self.report_type_dd)
        self.verticalLayout.addWidget(self.first_row_dropdown)
        self.second_row_dropdown = QtWidgets.QWidget(parent=self.dropdown_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.second_row_dropdown.setFont(font)
        self.second_row_dropdown.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: #084924;\n"
"    background-color: #FDC601;\n"
"    padding: 10px;\n"
"    text-align: left;\n"
"};")
        self.second_row_dropdown.setObjectName("second_row_dropdown")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.second_row_dropdown)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.second_row_dropdown)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/organization/icons/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.second_row_dropdown)
        self.pushButton_2.setIcon(icon2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout.addWidget(self.second_row_dropdown)
        self.generate_report_btn = QtWidgets.QPushButton(parent=self.dropdown_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.generate_report_btn.setFont(font)
        self.generate_report_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"    border: 2px solid #084924;\n"
"    border-radius: 10px;\n"
"    color: #084924;\n"
"    margin: 0px 10px 0px 10px;\n"
"};")
        self.generate_report_btn.setObjectName("generate_report_btn")
        self.verticalLayout.addWidget(self.generate_report_btn)
        spacerItem1 = QtWidgets.QSpacerItem(20, 402, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.buttom_container = QtWidgets.QWidget(parent=self.dropdown_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.buttom_container.setFont(font)
        self.buttom_container.setStyleSheet("QPushButton {\n"
"    border-radius: 10px;\n"
"    color: #084924;\n"
"    background-color: #FDC601;\n"
"    padding: 10px;\n"
"};")
        self.buttom_container.setObjectName("buttom_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.buttom_container)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.download_pdf_btn = QtWidgets.QPushButton(parent=self.buttom_container)
        self.download_pdf_btn.setObjectName("download_pdf_btn")
        self.horizontalLayout_3.addWidget(self.download_pdf_btn, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.download_excel_btn = QtWidgets.QPushButton(parent=self.buttom_container)
        self.download_excel_btn.setStyleSheet("QPushButton {\n"
"    color: white;\n"
"    background-color: #084924;\n"
"};")
        self.download_excel_btn.setObjectName("download_excel_btn")
        self.horizontalLayout_3.addWidget(self.download_excel_btn, 0, QtCore.Qt.AlignmentFlag.AlignBottom)
        self.verticalLayout.addWidget(self.buttom_container)
        self.horizontalLayout_4.addWidget(self.dropdown_container)
        self.preview_container = QtWidgets.QWidget(parent=self.options)
        self.preview_container.setObjectName("preview_container")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.preview_container)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.preview_label = QtWidgets.QLabel(parent=self.preview_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.preview_label.setFont(font)
        self.preview_label.setStyleSheet("QLabel {\n"
"    color: #084924;\n"
"};")
        self.preview_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.preview_label.setObjectName("preview_label")
        self.verticalLayout_2.addWidget(self.preview_label)
        self.preview_frame = QtWidgets.QFrame(parent=self.preview_container)
        self.preview_frame.setMinimumSize(QtCore.QSize(500, 550))
        self.preview_frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"    border: 1px solid #ccc;\n"
"};")
        self.preview_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.preview_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.preview_frame.setObjectName("preview_frame")
        self.verticalLayout_2.addWidget(self.preview_frame)
        self.horizontalLayout_4.addWidget(self.preview_container, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.options)
        self.verticalLayout_4.addWidget(self.main_container, 0, QtCore.Qt.AlignmentFlag.AlignTop)

        self.retranslateUi(generate_reports_widget)
        QtCore.QMetaObject.connectSlotsByName(generate_reports_widget)

    def retranslateUi(self, generate_reports_widget):
        _translate = QtCore.QCoreApplication.translate
        generate_reports_widget.setWindowTitle(_translate("generate_reports_widget", "Form"))
        self.header_laberl_reports.setText(_translate("generate_reports_widget", "Generate Reports"))
        self.back_btn_reports.setShortcut(_translate("generate_reports_widget", "Esc"))
        self.options_laberl.setText(_translate("generate_reports_widget", "Options"))
        self.select_org_dd.setCurrentText(_translate("generate_reports_widget", "Select Organizaiton"))
        self.select_org_dd.setItemText(0, _translate("generate_reports_widget", "Select Organizaiton"))
        self.report_type_dd.setCurrentText(_translate("generate_reports_widget", "Event History  (Default)"))
        self.report_type_dd.setItemText(0, _translate("generate_reports_widget", "Event History  (Default)"))
        self.report_type_dd.setItemText(1, _translate("generate_reports_widget", "Membership"))
        self.report_type_dd.setItemText(2, _translate("generate_reports_widget", "Officer List"))
        self.report_type_dd.setItemText(3, _translate("generate_reports_widget", "Summary"))
        self.pushButton.setText(_translate("generate_reports_widget", "Start Date"))
        self.pushButton_2.setText(_translate("generate_reports_widget", "End Date"))
        self.generate_report_btn.setText(_translate("generate_reports_widget", "Generate Report"))
        self.download_pdf_btn.setText(_translate("generate_reports_widget", "Download PDF"))
        self.download_excel_btn.setText(_translate("generate_reports_widget", "Download Excel"))
        self.preview_label.setText(_translate("generate_reports_widget", "Report Preview"))
