# Form implementation generated from reading ui file 'org_main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from . import resources_rc

class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1200, 800)
        Widget.setMinimumSize(QtCore.QSize(600, 500))
        self.main_layout = QtWidgets.QVBoxLayout(Widget)
        self.main_layout.setContentsMargins(10, 0, 10, 0)
        self.main_layout.setSpacing(0)
        self.main_layout.setObjectName("main_layout")
        self.stacked_widget = QtWidgets.QStackedWidget(parent=Widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stacked_widget.sizePolicy().hasHeightForWidth())
        self.stacked_widget.setSizePolicy(sizePolicy)
        self.stacked_widget.setObjectName("stacked_widget")
        self.landing_page = QtWidgets.QWidget()
        self.landing_page.setObjectName("landing_page")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.landing_page)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.burger_btn = QtWidgets.QPushButton(parent=self.landing_page)
        self.burger_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.burger_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.burger_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/organization/icons/burger_ic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.burger_btn.setIcon(icon)
        self.burger_btn.setIconSize(QtCore.QSize(40, 40))
        self.burger_btn.setObjectName("burger_btn")
        self.horizontalLayout_2.addWidget(self.burger_btn)
        self.header_label = QtWidgets.QLabel(parent=self.landing_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setKerning(True)
        self.header_label.setFont(font)
        self.header_label.setStyleSheet("QLabel {\n"
"    color: #084924;\n"
"};")
        self.header_label.setObjectName("header_label")
        self.horizontalLayout_2.addWidget(self.header_label)
        spacerItem = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.comboBox = QtWidgets.QComboBox(parent=self.landing_page)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setStyleSheet("QComboBox {\n"
"    border: none;\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    background-color: #084924;\n"
"    color: white;\n"
"    padding-left: 10px;\n"
"};")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.horizontalLayout_2.addWidget(self.comboBox)
        self.frame = QtWidgets.QFrame(parent=self.landing_page)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setStyleSheet("QFrame {\n"
"    border: 1px solid #084924;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"};")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.search_line = QtWidgets.QLineEdit(parent=self.frame)
        self.search_line.setObjectName("search_line")
        self.horizontalLayout.addWidget(self.search_line)
        self.search_btn = QtWidgets.QToolButton(parent=self.frame)
        self.search_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.search_btn.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
        self.search_btn.setStyleSheet("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/organization/icons/search_ic.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.search_btn.setIcon(icon1)
        self.search_btn.setIconSize(QtCore.QSize(30, 30))
        self.search_btn.setObjectName("search_btn")
        self.horizontalLayout.addWidget(self.search_btn)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.joined_container = QtWidgets.QFrame(parent=self.landing_page)
        self.joined_container.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joined_container.sizePolicy().hasHeightForWidth())
        self.joined_container.setSizePolicy(sizePolicy)
        self.joined_container.setMinimumSize(QtCore.QSize(0, 0))
        self.joined_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.joined_container.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"#joined_container {\n"
"    border: 1px solid #ccc;\n"
"    border-radius: 20px;\n"
"};")
        self.joined_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.joined_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.joined_container.setObjectName("joined_container")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.joined_container)
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetNoConstraint)
        self.verticalLayout_3.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.joined_label = QtWidgets.QLabel(parent=self.joined_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.joined_label.setFont(font)
        self.joined_label.setObjectName("joined_label")
        self.verticalLayout_7.addWidget(self.joined_label, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.hr_line = QtWidgets.QFrame(parent=self.joined_container)
        self.hr_line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.hr_line.setAutoFillBackground(False)
        self.hr_line.setStyleSheet("QFrame {\n"
"    background-color: #828282;\n"
"}")
        self.hr_line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hr_line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hr_line.setObjectName("hr_line")
        self.verticalLayout_7.addWidget(self.hr_line, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addLayout(self.verticalLayout_7)
        self.joined_org_scrollable = QtWidgets.QScrollArea(parent=self.joined_container)
        self.joined_org_scrollable.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };\n"
"\n"
"")
        self.joined_org_scrollable.setWidgetResizable(True)
        self.joined_org_scrollable.setObjectName("joined_org_scrollable")
        self.joined_org_scroll = QtWidgets.QWidget()
        self.joined_org_scroll.setGeometry(QtCore.QRect(0, 0, 1116, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.joined_org_scroll.sizePolicy().hasHeightForWidth())
        self.joined_org_scroll.setSizePolicy(sizePolicy)
        self.joined_org_scroll.setObjectName("joined_org_scroll")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.joined_org_scroll)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.joined_org_grid = QtWidgets.QGridLayout()
        self.joined_org_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.joined_org_grid.setHorizontalSpacing(20)
        self.joined_org_grid.setVerticalSpacing(40)
        self.joined_org_grid.setObjectName("joined_org_grid")
        self.verticalLayout_4.addLayout(self.joined_org_grid)
        self.joined_org_scrollable.setWidget(self.joined_org_scroll)
        self.verticalLayout_3.addWidget(self.joined_org_scrollable)
        self.verticalLayout_2.addWidget(self.joined_container)
        spacerItem1 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        self.verticalLayout_2.addItem(spacerItem1)
        self.other_container = QtWidgets.QFrame(parent=self.landing_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.other_container.sizePolicy().hasHeightForWidth())
        self.other_container.setSizePolicy(sizePolicy)
        self.other_container.setMinimumSize(QtCore.QSize(0, 0))
        self.other_container.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.other_container.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"#other_container {\n"
"    border: 1px solid #ccc;\n"
"};")
        self.other_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.other_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.other_container.setObjectName("other_container")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.other_container)
        self.verticalLayout_6.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.college_label = QtWidgets.QLabel(parent=self.other_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.college_label.setFont(font)
        self.college_label.setObjectName("college_label")
        self.verticalLayout_5.addWidget(self.college_label, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.hr_line_2 = QtWidgets.QFrame(parent=self.other_container)
        self.hr_line_2.setMaximumSize(QtCore.QSize(16777215, 1))
        self.hr_line_2.setStyleSheet("QFrame {\n"
"    background-color: #828282;\n"
"}")
        self.hr_line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.hr_line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.hr_line_2.setObjectName("hr_line_2")
        self.verticalLayout_5.addWidget(self.hr_line_2, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.college_org_scrollable = QtWidgets.QScrollArea(parent=self.other_container)
        self.college_org_scrollable.setStyleSheet("QWidget {\n"
"    border: none;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };")
        self.college_org_scrollable.setWidgetResizable(True)
        self.college_org_scrollable.setObjectName("college_org_scrollable")
        self.college_org_scroll = QtWidgets.QWidget()
        self.college_org_scroll.setGeometry(QtCore.QRect(0, 0, 1116, 266))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.college_org_scroll.sizePolicy().hasHeightForWidth())
        self.college_org_scroll.setSizePolicy(sizePolicy)
        self.college_org_scroll.setObjectName("college_org_scroll")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.college_org_scroll)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.college_org_grid = QtWidgets.QGridLayout()
        self.college_org_grid.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetMaximumSize)
        self.college_org_grid.setHorizontalSpacing(20)
        self.college_org_grid.setVerticalSpacing(40)
        self.college_org_grid.setObjectName("college_org_grid")
        self.verticalLayout_8.addLayout(self.college_org_grid)
        self.college_org_scrollable.setWidget(self.college_org_scroll)
        self.verticalLayout_6.addWidget(self.college_org_scrollable)
        self.verticalLayout_2.addWidget(self.other_container)
        self.stacked_widget.addWidget(self.landing_page)
        self.org_details = QtWidgets.QWidget()
        self.org_details.setObjectName("org_details")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.org_details)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.header_org_details = QtWidgets.QHBoxLayout()
        self.header_org_details.setObjectName("header_org_details")
        self.burger_btn__details = QtWidgets.QPushButton(parent=self.org_details)
        self.burger_btn__details.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.burger_btn__details.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.burger_btn__details.setText("")
        self.burger_btn__details.setIcon(icon)
        self.burger_btn__details.setIconSize(QtCore.QSize(40, 40))
        self.burger_btn__details.setObjectName("burger_btn__details")
        self.header_org_details.addWidget(self.burger_btn__details)
        self.header_label_2 = QtWidgets.QLabel(parent=self.org_details)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setKerning(True)
        self.header_label_2.setFont(font)
        self.header_label_2.setStyleSheet("QLabel {\n"
"    color: #084924;\n"
"};")
        self.header_label_2.setObjectName("header_label_2")
        self.header_org_details.addWidget(self.header_label_2)
        spacerItem2 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.header_org_details.addItem(spacerItem2)
        self.back_btn = QtWidgets.QPushButton(parent=self.org_details)
        self.back_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.back_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.back_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/organization/icons/Back IC.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.back_btn.setIcon(icon2)
        self.back_btn.setIconSize(QtCore.QSize(30, 30))
        self.back_btn.setObjectName("back_btn")
        self.header_org_details.addWidget(self.back_btn)
        self.verticalLayout_15.addLayout(self.header_org_details)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.org_details_container = QtWidgets.QFrame(parent=self.org_details)
        self.org_details_container.setMinimumSize(QtCore.QSize(250, 0))
        self.org_details_container.setMaximumSize(QtCore.QSize(500, 16777215))
        self.org_details_container.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#org_details_container {\n"
"    border: 1px solid #ccc;\n"
"}\n"
"\n"
"QPushButton {\n"
"    padding: 5px 0px 5px 0px;\n"
"    border: none;\n"
"    color: white;\n"
"    background-color: #084924;\n"
"}\n"
"\n"
"#scroll_area_contents_2 {\n"
"    background-color: white;\n"
"}\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };")
        self.org_details_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.org_details_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.org_details_container.setObjectName("org_details_container")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.org_details_container)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.header = QtWidgets.QLabel(parent=self.org_details_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.verticalLayout_19.addWidget(self.header)
        self.line = QtWidgets.QFrame(parent=self.org_details_container)
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("QFrame {\n"
"    background-color: #4F4F4F;\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_19.addWidget(self.line)
        self.scrollArea = QtWidgets.QScrollArea(parent=self.org_details_container)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scroll_area_contents_2 = QtWidgets.QWidget()
        self.scroll_area_contents_2.setGeometry(QtCore.QRect(0, 0, 334, 650))
        self.scroll_area_contents_2.setStyleSheet("")
        self.scroll_area_contents_2.setObjectName("scroll_area_contents_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scroll_area_contents_2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.status_btn = QtWidgets.QPushButton(parent=self.scroll_area_contents_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.status_btn.setFont(font)
        self.status_btn.setStyleSheet("QPushButton {\n"
"        border-top-left-radius: 10px; \n"
"        border-top-right-radius: 10px;\n"
"};\n"
"")
        self.status_btn.setObjectName("status_btn")
        self.verticalLayout.addWidget(self.status_btn)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.frame_2 = QtWidgets.QFrame(parent=self.scroll_area_contents_2)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.logo = QtWidgets.QLabel(parent=self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.logo.sizePolicy().hasHeightForWidth())
        self.logo.setSizePolicy(sizePolicy)
        self.logo.setMinimumSize(QtCore.QSize(200, 200))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.logo.setFont(font)
        self.logo.setStyleSheet("QLabel {\n"
"    text-align: center;\n"
"};")
        self.logo.setScaledContents(True)
        self.logo.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.logo.setObjectName("logo")
        self.horizontalLayout_7.addWidget(self.logo)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.verticalLayout.addWidget(self.frame_2)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.org_name = QtWidgets.QLabel(parent=self.scroll_area_contents_2)
        self.org_name.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.org_name.setFont(font)
        self.org_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.org_name.setObjectName("org_name")
        self.verticalLayout.addWidget(self.org_name, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.line_6 = QtWidgets.QFrame(parent=self.scroll_area_contents_2)
        self.line_6.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_6.setStyleSheet("QFrame {\n"
"    background-color: #4F4F4F;\n"
"}")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.org_type = QtWidgets.QLabel(parent=self.scroll_area_contents_2)
        self.org_type.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.org_type.setFont(font)
        self.org_type.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.org_type.setObjectName("org_type")
        self.verticalLayout.addWidget(self.org_type, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.derscription_container = QtWidgets.QFrame(parent=self.scroll_area_contents_2)
        self.derscription_container.setStyleSheet("QLabel {\n"
"    color: #4F4F4F;\n"
"};")
        self.derscription_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.derscription_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.derscription_container.setObjectName("derscription_container")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.derscription_container)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.brief_btn = QtWidgets.QPushButton(parent=self.derscription_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.brief_btn.setFont(font)
        self.brief_btn.setStyleSheet("QPushButton {\n"
"        border-top-left-radius: 10px; \n"
"        border-top-right-radius: 10px;\n"
"};\n"
"")
        self.brief_btn.setObjectName("brief_btn")
        self.verticalLayout_10.addWidget(self.brief_btn)
        self.brief_label = QtWidgets.QLabel(parent=self.derscription_container)
        self.brief_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.brief_label.setObjectName("brief_label")
        self.verticalLayout_10.addWidget(self.brief_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.obj_btn = QtWidgets.QPushButton(parent=self.derscription_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.obj_btn.setFont(font)
        self.obj_btn.setStyleSheet("QPushButton {\n"
"        border-top-left-radius: 10px; \n"
"        border-top-right-radius: 10px;\n"
"};\n"
"")
        self.obj_btn.setObjectName("obj_btn")
        self.verticalLayout_10.addWidget(self.obj_btn)
        self.obj_label = QtWidgets.QLabel(parent=self.derscription_container)
        self.obj_label.setMaximumSize(QtCore.QSize(300, 16777215))
        self.obj_label.setObjectName("obj_label")
        self.verticalLayout_10.addWidget(self.obj_label, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.branch_btn = QtWidgets.QPushButton(parent=self.derscription_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.branch_btn.setFont(font)
        self.branch_btn.setStyleSheet("QPushButton {\n"
"        border-top-left-radius: 10px; \n"
"        border-top-right-radius: 10px;\n"
"};\n"
"")
        self.branch_btn.setObjectName("branch_btn")
        self.verticalLayout_10.addWidget(self.branch_btn)
        self.obj_label_2 = QtWidgets.QLabel(parent=self.derscription_container)
        self.obj_label_2.setMaximumSize(QtCore.QSize(300, 16777215))
        self.obj_label_2.setObjectName("obj_label_2")
        self.verticalLayout_10.addWidget(self.obj_label_2, 0, QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignVCenter)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_10.addItem(spacerItem8)
        self.verticalLayout.addWidget(self.derscription_container)
        self.scrollArea.setWidget(self.scroll_area_contents_2)
        self.verticalLayout_19.addWidget(self.scrollArea)
        self.horizontalLayout_6.addWidget(self.org_details_container)
        spacerItem9 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem9)
        self.officers_frame = QtWidgets.QFrame(parent=self.org_details)
        self.officers_frame.setMinimumSize(QtCore.QSize(500, 0))
        self.officers_frame.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#officers_frame {\n"
"    border: 1px solid #ccc;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    padding: 5px 10px 5px 10px;\n"
"}\n"
"\n"
"QComboBox {\n"
"    border: none;\n"
"    padding: 5px 10px 5px 10px;\n"
"};")
        self.officers_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.officers_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.officers_frame.setObjectName("officers_frame")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.officers_frame)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.header_2 = QtWidgets.QLabel(parent=self.officers_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.header_2.setFont(font)
        self.header_2.setObjectName("header_2")
        self.horizontalLayout_3.addWidget(self.header_2)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.view_members_btn = QtWidgets.QPushButton(parent=self.officers_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setUnderline(True)
        self.view_members_btn.setFont(font)
        self.view_members_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.view_members_btn.setObjectName("view_members_btn")
        self.horizontalLayout_3.addWidget(self.view_members_btn)
        self.verticalLayout_12.addLayout(self.horizontalLayout_3)
        self.line_3 = QtWidgets.QFrame(parent=self.officers_frame)
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("QFrame {\n"
"    background-color: #4F4F4F;\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_12.addWidget(self.line_3, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.officers_scroll_area = QtWidgets.QScrollArea(parent=self.officers_frame)
        self.officers_scroll_area.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };")
        self.officers_scroll_area.setWidgetResizable(True)
        self.officers_scroll_area.setObjectName("officers_scroll_area")
        self.scroll_area_contents = QtWidgets.QWidget()
        self.scroll_area_contents.setGeometry(QtCore.QRect(0, 0, 476, 602))
        self.scroll_area_contents.setObjectName("scroll_area_contents")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.scroll_area_contents)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.officer_cards_grid = QtWidgets.QGridLayout()
        self.officer_cards_grid.setObjectName("officer_cards_grid")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.officer_cards_grid.addItem(spacerItem11, 0, 1, 1, 1)
        self.verticalLayout_11.addLayout(self.officer_cards_grid)
        self.officers_scroll_area.setWidget(self.scroll_area_contents)
        self.verticalLayout_12.addWidget(self.officers_scroll_area)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label = QtWidgets.QLabel(parent=self.officers_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_4.addWidget(self.label)
        spacerItem12 = QtWidgets.QSpacerItem(273, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem12)
        self.officer_history_dp = QtWidgets.QComboBox(parent=self.officers_frame)
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.officer_history_dp.setFont(font)
        self.officer_history_dp.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.officer_history_dp.setObjectName("officer_history_dp")
        self.officer_history_dp.addItem("")
        self.horizontalLayout_4.addWidget(self.officer_history_dp)
        self.verticalLayout_12.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6.addWidget(self.officers_frame)
        spacerItem13 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem13)
        self.events_container = QtWidgets.QFrame(parent=self.org_details)
        self.events_container.setMinimumSize(QtCore.QSize(250, 0))
        self.events_container.setMaximumSize(QtCore.QSize(400, 16777215))
        self.events_container.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#events_container {\n"
"    border: 1px solid #ccc;\n"
"}")
        self.events_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.events_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.events_container.setObjectName("events_container")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.events_container)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.header_3 = QtWidgets.QLabel(parent=self.events_container)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.header_3.setFont(font)
        self.header_3.setObjectName("header_3")
        self.horizontalLayout_5.addWidget(self.header_3)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem14)
        self.calendar_btn = QtWidgets.QPushButton(parent=self.events_container)
        font = QtGui.QFont()
        font.setUnderline(False)
        self.calendar_btn.setFont(font)
        self.calendar_btn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.calendar_btn.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"};")
        self.calendar_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/organization/icons/calendar.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.calendar_btn.setIcon(icon3)
        self.calendar_btn.setIconSize(QtCore.QSize(30, 30))
        self.calendar_btn.setObjectName("calendar_btn")
        self.horizontalLayout_5.addWidget(self.calendar_btn)
        self.verticalLayout_13.addLayout(self.horizontalLayout_5)
        self.line_4 = QtWidgets.QFrame(parent=self.events_container)
        self.line_4.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_4.setStyleSheet("QFrame {\n"
"    background-color: black;\n"
"}")
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout_13.addWidget(self.line_4)
        self.scroll_area_events = QtWidgets.QScrollArea(parent=self.events_container)
        self.scroll_area_events.setStyleSheet("QWidget {\n"
"    background-color: white;\n"
"    border: none;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };")
        self.scroll_area_events.setWidgetResizable(True)
        self.scroll_area_events.setObjectName("scroll_area_events")
        self.events_container_2 = QtWidgets.QWidget()
        self.events_container_2.setGeometry(QtCore.QRect(0, 0, 226, 628))
        self.events_container_2.setObjectName("events_container_2")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.events_container_2)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.scroll_area_events.setWidget(self.events_container_2)
        self.verticalLayout_13.addWidget(self.scroll_area_events)
        self.horizontalLayout_6.addWidget(self.events_container)
        self.verticalLayout_15.addLayout(self.horizontalLayout_6)
        self.stacked_widget.addWidget(self.org_details)
        self.view_members = QtWidgets.QWidget()
        self.view_members.setObjectName("view_members")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.view_members)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.members_header = QtWidgets.QHBoxLayout()
        self.members_header.setObjectName("members_header")
        self.burger_btn_2 = QtWidgets.QPushButton(parent=self.view_members)
        self.burger_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        self.burger_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}")
        self.burger_btn_2.setText("")
        self.burger_btn_2.setIcon(icon)
        self.burger_btn_2.setIconSize(QtCore.QSize(40, 40))
        self.burger_btn_2.setObjectName("burger_btn_2")
        self.members_header.addWidget(self.burger_btn_2)
        self.header_label_3 = QtWidgets.QLabel(parent=self.view_members)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setKerning(True)
        self.header_label_3.setFont(font)
        self.header_label_3.setStyleSheet("QLabel {\n"
"    color: #084924;\n"
"};")
        self.header_label_3.setObjectName("header_label_3")
        self.members_header.addWidget(self.header_label_3)
        spacerItem15 = QtWidgets.QSpacerItem(332, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.members_header.addItem(spacerItem15)
        self.search_container = QtWidgets.QFrame(parent=self.view_members)
        self.search_container.setMaximumSize(QtCore.QSize(16777215, 40))
        self.search_container.setStyleSheet("QFrame {\n"
"    border: 1px solid #084924;\n"
"    background-color: white;\n"
"    border-radius: 20px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    background-color: transparent;\n"
"    border: none;\n"
"};")
        self.search_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.search_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.search_container.setObjectName("search_container")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.search_container)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.search_line_3 = QtWidgets.QLineEdit(parent=self.search_container)
        self.search_line_3.setObjectName("search_line_3")
        self.horizontalLayout_9.addWidget(self.search_line_3)
        self.search_btn_3 = QtWidgets.QToolButton(parent=self.search_container)
        self.search_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.search_btn_3.setIcon(icon1)
        self.search_btn_3.setIconSize(QtCore.QSize(30, 30))
        self.search_btn_3.setObjectName("search_btn_3")
        self.horizontalLayout_9.addWidget(self.search_btn_3)
        self.members_header.addWidget(self.search_container)
        self.back_btn_member = QtWidgets.QPushButton(parent=self.view_members)
        self.back_btn_member.setStyleSheet("QPushButton {\n"
"    background-color: transparent;\n"
"}")
        self.back_btn_member.setText("")
        self.back_btn_member.setIcon(icon2)
        self.back_btn_member.setIconSize(QtCore.QSize(30, 30))
        self.back_btn_member.setObjectName("back_btn_member")
        self.members_header.addWidget(self.back_btn_member)
        self.verticalLayout_18.addLayout(self.members_header)
        self.list_container = QtWidgets.QFrame(parent=self.view_members)
        self.list_container.setStyleSheet("QFrame {\n"
"    background-color: white;\n"
"    border-radius: 10px;\n"
"}\n"
"\n"
"#list_container {\n"
"    border: 1px solid #ccc;\n"
"};")
        self.list_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.list_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.list_container.setObjectName("list_container")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.list_container)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.header_4 = QtWidgets.QWidget(parent=self.list_container)
        self.header_4.setObjectName("header_4")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.header_4)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(parent=self.header_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.line_5 = QtWidgets.QFrame(parent=self.header_4)
        self.line_5.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_5.setStyleSheet("QFrame {\n"
"    background-color: #4F4F4F;\n"
"}")
        self.line_5.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout_16.addWidget(self.line_5)
        self.verticalLayout_17.addWidget(self.header_4)
        self.list_view = QtWidgets.QTableView(parent=self.list_container)
        self.list_view.setStyleSheet("QTableView {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    background-color: white;\n"
"}\n"
"\n"
"\n"
"QScrollBar:vertical {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                width: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:vertical {\n"
"                background: #ccc;\n"
"                min-height: 20px;\n"
"                border-radius: 6px;\n"
"            }\n"
"            QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"                height: 0;\n"
"                background: none;\n"
"            }\n"
"            QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"                background: none;\n"
"            }\n"
"            \n"
"            QScrollBar:horizontal {\n"
"                border: none;\n"
"                background: #f0f0f0;\n"
"                height: 12px;\n"
"                margin: 0;\n"
"            }\n"
"            QScrollBar::handle:horizontal {\n"
"                background: #ccc;\n"
"                min-width: 20px;\n"
"                border-radius: 6px;\n"
"            };")
        self.list_view.setObjectName("list_view")
        self.verticalLayout_17.addWidget(self.list_view)
        self.verticalLayout_18.addWidget(self.list_container)
        self.stacked_widget.addWidget(self.view_members)
        self.main_layout.addWidget(self.stacked_widget)

        self.retranslateUi(Widget)
        self.stacked_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.header_label.setText(_translate("Widget", "Organization"))
        self.comboBox.setItemText(0, _translate("Widget", "Organizations"))
        self.comboBox.setItemText(1, _translate("Widget", "Branches"))
        self.search_btn.setText(_translate("Widget", "..."))
        self.search_btn.setShortcut(_translate("Widget", "Return, Enter"))
        self.joined_label.setText(_translate("Widget", "Joined Organization(s)"))
        self.college_label.setText(_translate("Widget", "College Organization(s)"))
        self.header_label_2.setText(_translate("Widget", "Organization"))
        self.back_btn.setShortcut(_translate("Widget", "Esc"))
        self.header.setText(_translate("Widget", "Organization Details"))
        self.status_btn.setText(_translate("Widget", "Active"))
        self.logo.setText(_translate("Widget", "Logo"))
        self.org_name.setText(_translate("Widget", "OrgName"))
        self.org_type.setText(_translate("Widget", "OrgType"))
        self.brief_btn.setText(_translate("Widget", "Brief Overview"))
        self.brief_label.setText(_translate("Widget", "BriefContent"))
        self.obj_btn.setText(_translate("Widget", "Objectives"))
        self.obj_label.setText(_translate("Widget", "ObjectivesContent"))
        self.branch_btn.setText(_translate("Widget", "Branches"))
        self.obj_label_2.setText(_translate("Widget", "BranchList"))
        self.header_2.setText(_translate("Widget", "Organization Officers"))
        self.view_members_btn.setText(_translate("Widget", "View Members"))
        self.label.setText(_translate("Widget", "Semester"))
        self.officer_history_dp.setItemText(0, _translate("Widget", "Officer History"))
        self.header_3.setText(_translate("Widget", "Upcoming Events"))
        self.header_label_3.setText(_translate("Widget", "Organization"))
        self.search_btn_3.setText(_translate("Widget", "..."))
        self.search_btn_3.setShortcut(_translate("Widget", "Return, Enter"))
        self.back_btn_member.setShortcut(_translate("Widget", "Esc"))
        self.label_2.setText(_translate("Widget", "Member List"))
