# Generated by Django 5.2.5 on 2025-11-30 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyFeedbackMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('midterm_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('final_term_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('re_exam', models.CharField(blank=True, max_length=4, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('withdrawn', 'Withdrawn')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='GWA',
            fields=[
                ('gwa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gwa', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
