# Generated by Django 5.2.5 on 2025-11-25 18:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0010_remove_section_unique_section_section_unique_section'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FinalGrade',
            fields=[
                ('grade_id', models.AutoField(primary_key=True, serialize=False)),
                ('midterm_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('final_term_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('re_exam', models.CharField(blank=True, max_length=4, null=True)),
                ('final_grade', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('incomplete', 'Incomplete'), ('withdrawn', 'Withdrawn')], max_length=12)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='Academics.course')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='Academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FacultyFeedbackMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('unread', 'Unread'), ('read', 'Read')], default='unread', max_length=8)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to='Progress.finalgrade')),
            ],
        ),
        migrations.CreateModel(
            name='GWA',
            fields=[
                ('gwa_id', models.AutoField(primary_key=True, serialize=False)),
                ('gwa', models.DecimalField(decimal_places=4, max_digits=5)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwa_records', to='Academics.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwa_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
