# Generated by Django 5.2.5 on 2025-11-30 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0002_initial'),
        ('Progress', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='facultyfeedbackmessage',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyfeedbackmessage',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='Academics.course'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='finalgrade',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_grades', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='facultyfeedbackmessage',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to='Progress.finalgrade'),
        ),
        migrations.AddField(
            model_name='gwa',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwa_records', to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='gwa',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gwa_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='gwa',
            unique_together={('student', 'semester')},
        ),
    ]
