# Generated by Django 5.2.5 on 2025-12-01 20:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Progress', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultyfeedbackmessage',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback_messages', to='Progress.finalgrade'),
        ),
    ]
