# Generated by Django 5.2.5 on 2025-12-08 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_initial'),
        ('Progress', '0003_alter_facultyfeedbackmessage_grade'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassScheduleInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('schedule', models.CharField(blank=True, default='', max_length=200)),
                ('room', models.CharField(blank=True, default='', max_length=100)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('class_instance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_info', to='Academics.class')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_updates', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
