# Generated by Django 5.2.7 on 2025-12-01 02:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_conversationhide'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='conversationhide',
            options={'verbose_name': 'Hidden Conversation', 'verbose_name_plural': 'Hidden Conversations'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages'},
        ),
        migrations.AddField(
            model_name='conversation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, help_text='Whether the receiver has read this message'),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='creator',
            field=models.ForeignKey(help_text='User who initiated the conversation', on_delete=django.db.models.deletion.CASCADE, related_name='created_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='participants',
            field=models.ManyToManyField(blank=True, help_text='Users involved in this conversation', related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='conversation',
            name='title',
            field=models.CharField(blank=True, help_text='Optional title for the conversation', max_length=255),
        ),
        migrations.AlterField(
            model_name='conversationhide',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_by', to='Messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='conversationhide',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hidden_conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='message_attachments/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(help_text='Message body content'),
        ),
        migrations.AlterField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(blank=True, help_text='Conversation this message belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='Messaging.conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='department',
            field=models.CharField(default='General', help_text='Department context for the message', max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_broadcast',
            field=models.BooleanField(default=False, help_text='Whether this message is sent to multiple recipients'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('normal', 'Normal'), ('inquiry', 'Inquiry'), ('announcement', 'Announcement'), ('broadcast', 'Broadcast')], default='normal', help_text='Type of message (inquiry, announcement, etc.)', max_length=50),
        ),
        migrations.AlterField(
            model_name='message',
            name='priority',
            field=models.CharField(choices=[('urgent', 'Urgent'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', help_text='Priority level of the message', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(blank=True, help_text='Primary receiver (null if broadcast)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='User who sent the message', on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_name',
            field=models.CharField(blank=True, help_text='Cached sender name for display', max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('resolved', 'Resolved'), ('archived', 'Archived')], default='pending', help_text='Current status of the message', max_length=10),
        ),
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(help_text='Message subject line', max_length=255),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'created_at'], name='Messaging_m_sender__f98b6d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['receiver', 'created_at'], name='Messaging_m_receive_386198_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', 'created_at'], name='Messaging_m_convers_96f6af_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type'], name='Messaging_m_message_c1bc27_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['is_read'], name='Messaging_m_is_read_fbb965_idx'),
        ),
    ]
