# Generated by Django 5.2.7 on 2025-12-01 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0003_conversationhide'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='group_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='conversation',
            name='type',
            field=models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], default='direct', max_length=10),
        ),
    ]
