# Generated by Django 5.2.7 on 2025-12-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0004_alter_conversation_options_and_more'),
        ('Messaging', '0004_conversation_group_name_conversation_type'),
    ]

    operations = [
    ]
