# Generated by Django 5.2.7 on 2025-12-03 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0005_merge_20251204_0705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conversation',
            options={},
        ),
        migrations.AlterModelOptions(
            name='conversationhide',
            options={},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='Messaging_m_sender__f98b6d_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='Messaging_m_receive_386198_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='Messaging_m_convers_96f6af_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='Messaging_m_message_c1bc27_idx',
        ),
        migrations.RemoveIndex(
            model_name='message',
            name='Messaging_m_is_read_fbb965_idx',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='group_name',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='conversation',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='message',
            name='is_read',
        ),
    ]
