# Generated by Django 5.2.7 on 2025-12-03 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Messaging', '0007_alter_conversation_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='conversation_type',
            field=models.CharField(choices=[('one_to_one', 'One to One'), ('group', 'Group')], default='one_to_one', max_length=20),
        ),
    ]
