# Generated by Django 5.2.5 on 2025-11-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='behavioral_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='house',
            name='competitive_points',
            field=models.IntegerField(default=0),
        ),
    ]
