# Generated by Django 5.2.5 on 2025-12-02 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CalendarEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=120)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('all_day', models.BooleanField(default=False)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('org_status', models.CharField(blank=True, max_length=10)),
                ('org_id', models.IntegerField(blank=True, null=True)),
                ('section_id', models.IntegerField(blank=True, null=True)),
                ('semester_id', models.IntegerField(blank=True, null=True)),
                ('source_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='Calendar.calendarentry')),
                ('performed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'calendar_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'holidays',
                'ordering': ['date'],
            },
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['start_at'], name='Calendar_ca_start_a_69e93a_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['end_at'], name='Calendar_ca_end_at_cf4f3f_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['section_id'], name='Calendar_ca_section_1f3118_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['semester_id'], name='Calendar_ca_semeste_5e70a0_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['org_id'], name='Calendar_ca_org_id_6c2354_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['is_public'], name='Calendar_ca_is_publ_3f8a47_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarentry',
            constraint=models.UniqueConstraint(fields=('source_ct', 'source_id', 'start_at', 'end_at'), name='unique_source_calendar_entry'),
        ),
        migrations.AddIndex(
            model_name='calendarlogs',
            index=models.Index(fields=['action'], name='calendar_lo_action_ed0384_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarlogs',
            index=models.Index(fields=['timestamp'], name='calendar_lo_timesta_774e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holidays_date_c1d23c_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_holiday_per_date'),
        ),
    ]
