# Generated by Django 5.2.5 on 2025-12-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Calendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='calendarlogs',
            name='performed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='holiday',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['start_at'], name='calendar_en_start_a_ed1c80_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['end_at'], name='calendar_en_end_at_9f0bdc_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['section_id'], name='calendar_en_section_ab78ce_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['semester_id'], name='calendar_en_semeste_7b3ed3_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['org_id'], name='calendar_en_org_id_e23357_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarentry',
            index=models.Index(fields=['is_public'], name='calendar_en_is_publ_a9eba5_idx'),
        ),
        migrations.AddConstraint(
            model_name='calendarentry',
            constraint=models.UniqueConstraint(fields=('source_ct', 'source_id', 'start_at', 'end_at'), name='unique_source_calendar_entry'),
        ),
        migrations.AddIndex(
            model_name='calendarlogs',
            index=models.Index(fields=['action'], name='calendar_lo_action_ed0384_idx'),
        ),
        migrations.AddIndex(
            model_name='calendarlogs',
            index=models.Index(fields=['timestamp'], name='calendar_lo_timesta_774e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='holiday',
            index=models.Index(fields=['date'], name='holidays_date_c1d23c_idx'),
        ),
        migrations.AddConstraint(
            model_name='holiday',
            constraint=models.UniqueConstraint(fields=('name', 'date'), name='unique_holiday_per_date'),
        ),
    ]
