# Form implementation generated from reading ui file 'message_card.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(881, 569)
        self.frame_container = QtWidgets.QFrame(parent=Form)
        self.frame_container.setGeometry(QtCore.QRect(0, 200, 881, 121))
        self.frame_container.setStyleSheet("QFrame#frame_container {\n"
"    background-color: white;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.frame_container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_container.setObjectName("frame_container")
        self.line_9 = QtWidgets.QFrame(parent=self.frame_container)
        self.line_9.setGeometry(QtCore.QRect(0, 110, 881, 16))
        self.line_9.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_9.setObjectName("line_9")
        self.label_recipient = QtWidgets.QLabel(parent=self.frame_container)
        self.label_recipient.setGeometry(QtCore.QRect(30, 10, 92, 21))
        self.label_recipient.setStyleSheet("#label_recipient {\n"
"    font-size: 16px;\n"
"    font-weight: bold;\n"
"}")
        self.label_recipient.setObjectName("label_recipient")
        self.label_status = QtWidgets.QLabel(parent=self.frame_container)
        self.label_status.setGeometry(QtCore.QRect(130, 10, 51, 21))
        self.label_status.setStyleSheet("#label_status {\n"
"    background-color: yellow;\n"
"    color: black;\n"
"    font-weight: bold;\n"
"    text-align:center;\n"
"    border-radius: 10px;  /* Add border-radius for rounded corners */\n"
"    border: 1px solid #FFCC00;  /* Optional: Add border color to make the rounded effect stand out */\n"
"}\n"
"")
        self.label_status.setObjectName("label_status")
        self.widget = QtWidgets.QWidget(parent=self.frame_container)
        self.widget.setGeometry(QtCore.QRect(820, 20, 46, 81))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_day = QtWidgets.QLabel(parent=self.widget)
        self.label_day.setStyleSheet("#label_day{\n"
"    color: gray;\n"
"    font-size: 10px;\n"
"}")
        self.label_day.setObjectName("label_day")
        self.verticalLayout.addWidget(self.label_day)
        self.label_stat1 = QtWidgets.QLabel(parent=self.widget)
        self.label_stat1.setStyleSheet("#label_stat1{\n"
"    color: gray;\n"
"    font-size: 10px;\n"
"}")
        self.label_stat1.setObjectName("label_stat1")
        self.verticalLayout.addWidget(self.label_stat1)
        self.widget1 = QtWidgets.QWidget(parent=self.frame_container)
        self.widget1.setGeometry(QtCore.QRect(30, 40, 611, 71))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_subject = QtWidgets.QLabel(parent=self.widget1)
        self.label_subject.setObjectName("label_subject")
        self.verticalLayout_2.addWidget(self.label_subject)
        self.label_body = QtWidgets.QLabel(parent=self.widget1)
        self.label_body.setObjectName("label_body")
        self.verticalLayout_2.addWidget(self.label_body)
        self.line_10 = QtWidgets.QFrame(parent=Form)
        self.line_10.setGeometry(QtCore.QRect(0, 190, 881, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_10.setObjectName("line_10")
        self.widget2 = QtWidgets.QWidget(parent=Form)
        self.widget2.setGeometry(QtCore.QRect(0, 0, 2, 2))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_recipient.setText(_translate("Form", "Andre Louie"))
        self.label_status.setText(_translate("Form", "Pending"))
        self.label_day.setText(_translate("Form", "1d Ago"))
        self.label_stat1.setText(_translate("Form", "Pending"))
        self.label_subject.setText(_translate("Form", "sample subject"))
        self.label_body.setText(_translate("Form", "sample body "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
