# Form implementation generated from reading ui file 'message_compose.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(955, 637)
        self.message_frame = QtWidgets.QFrame(parent=Form)
        self.message_frame.setGeometry(QtCore.QRect(210, 130, 531, 421))
        self.message_frame.setStyleSheet("QFrame#message_frame {\n"
"    background-color: white;\n"
"    border-radius: 16px;\n"
"    border: 1px solid #e0e0e0;\n"
"    padding: 10px;\n"
"}\n"
"")
        self.message_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.message_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.message_frame.setObjectName("message_frame")
        self.label_header = QtWidgets.QLabel(parent=self.message_frame)
        self.label_header.setGeometry(QtCore.QRect(20, 10, 361, 21))
        self.label_header.setStyleSheet("QLabel#label_header{\n"
"    color: #084924;           /* Dark green text */\n"
"    font-size: 15px;          /* Large font */\n"
"    font-weight: bold;        /* Bold text */\n"
"    background-color: transparent;\n"
"}\n"
"")
        self.label_header.setObjectName("label_header")
        self.line = QtWidgets.QFrame(parent=self.message_frame)
        self.line.setGeometry(QtCore.QRect(0, 30, 671, 21))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.btn_close = QtWidgets.QPushButton(parent=self.message_frame)
        self.btn_close.setGeometry(QtCore.QRect(614, 10, 41, 24))
        self.btn_close.setStyleSheet("#btn_close{\n"
"    background-color: transparent;\n"
"    color: #808080;\n"
"    padding: 6px 14px;\n"
"    border: 1px solid #cccccc;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btn_close:hover {\n"
"     background-color: #FF0000;\n"
"    color:white;\n"
"}")
        self.btn_close.setObjectName("btn_close")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.message_frame)
        self.layoutWidget_2.setGeometry(QtCore.QRect(240, 380, 276, 32))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_cancel = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.btn_cancel.setStyleSheet("#btn_cancel{\n"
"    background-color: #transparent;\n"
"    color: black;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btn_cancel:hover {\n"
"    background-color: #FF0000;\n"
"    color:white;\n"
"}\n"
"")
        self.btn_cancel.setObjectName("btn_cancel")
        self.horizontalLayout_2.addWidget(self.btn_cancel)
        self.btn_send = QtWidgets.QPushButton(parent=self.layoutWidget_2)
        self.btn_send.setStyleSheet("#btn_send {\n"
"    background-color: #0056b3;\n"
"    color: white;\n"
"    padding: 6px 14px;\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"#btn_send:hover {\n"
"    background-color: #094924;\n"
"}\n"
"")
        self.btn_send.setObjectName("btn_send")
        self.horizontalLayout_2.addWidget(self.btn_send)
        self.lineEdit_to = QtWidgets.QLineEdit(parent=self.message_frame)
        self.lineEdit_to.setGeometry(QtCore.QRect(20, 70, 491, 31))
        self.lineEdit_to.setStyleSheet("QLineEdit#lineEdit_to {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Slightly smaller radius for a modern, clean look */\n"
"    border: 1px solid #ccc; /* Soft light gray border */\n"
"    padding: 5px 7px; /* Added padding for better spacing */\n"
"    font-size: 14px; /* Adjust font size for readability */\n"
"    color: #333; /* Dark gray text color for readability */\n"
"}\n"
"\n"
"QLineEdit#lineEdit_to:focus {\n"
"    border: 1px solid #084924; /* Blue border when focused (modern feel) */\n"
"    box-shadow: 0 0 5px rgba(76, 158, 255, 0.5); /* Soft shadow effect on focus */\n"
"}\n"
"\n"
"QLineEdit#lineEdit_to:hover {\n"
"    border: 1px solid #888; /* Darker border when hovered */\n"
"    background-color: #e9e9e9; /* Slightly darker background on hover */\n"
"}\n"
"")
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.label = QtWidgets.QLabel(parent=self.message_frame)
        self.label.setGeometry(QtCore.QRect(20, 50, 49, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.message_frame)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 49, 16))
        self.label_2.setObjectName("label_2")
        self.lineEdit_subject = QtWidgets.QLineEdit(parent=self.message_frame)
        self.lineEdit_subject.setGeometry(QtCore.QRect(20, 130, 491, 31))
        self.lineEdit_subject.setStyleSheet("QLineEdit#lineEdit_subject {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Slightly smaller radius for a modern, clean look */\n"
"    border: 1px solid #ccc; /* Soft light gray border */\n"
"    padding: 5px 7px; /* Added padding for better spacing */\n"
"    font-size: 14px; /* Adjust font size for readability */\n"
"    color: #333; /* Dark gray text color for readability */\n"
"}\n"
"\n"
"QLineEdit#lineEdit_subject:focus {\n"
"    border: 1px solid #084924; /* Blue border when focused (modern feel) */\n"
"    box-shadow: 0 0 5px rgba(76, 158, 255, 0.5); /* Soft shadow effect on focus */\n"
"}\n"
"\n"
"QLineEdit#lineEdit_subject:hover {\n"
"    border: 1px solid #888; /* Darker border when hovered */\n"
"    background-color: #e9e9e9; /* Slightly darker background on hover */\n"
"}\n"
"")
        self.lineEdit_subject.setObjectName("lineEdit_subject")
        self.label_3 = QtWidgets.QLabel(parent=self.message_frame)
        self.label_3.setGeometry(QtCore.QRect(20, 170, 49, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.message_frame)
        self.label_4.setGeometry(QtCore.QRect(20, 220, 49, 16))
        self.label_4.setObjectName("label_4")
        self.textEdit_msg = QtWidgets.QTextEdit(parent=self.message_frame)
        self.textEdit_msg.setGeometry(QtCore.QRect(20, 240, 491, 131))
        self.textEdit_msg.setStyleSheet("QTextEdit#textEdit_msg {\n"
"    background-color: #f0f0f0; /* Light gray background */\n"
"    border-radius: 5px; /* Slightly smaller radius for a modern, clean look */\n"
"    border: 1px solid #ccc; /* Soft light gray border */\n"
"    padding: 5px 7px; /* Added padding for better spacing */\n"
"    font-size: 14px; /* Adjust font size for readability */\n"
"    color: #333; /* Dark gray text color for readability */\n"
"}\n"
"\n"
"QTextEdit#textEdit_msg:focus {\n"
"    border: 1px solid #084924; /* Blue border when focused (modern feel) */\n"
"    box-shadow: 0 0 5px rgba(76, 158, 255, 0.5); /* Soft shadow effect on focus */\n"
"}\n"
"\n"
"QTextEdit#textEdit_msgt:hover {\n"
"    border: 1px solid #888; /* Darker border when hovered */\n"
"    background-color: #e9e9e9; /* Slightly darker background on hover */\n"
"}\n"
"")
        self.textEdit_msg.setObjectName("textEdit_msg")
        self.comboBox_prio = QtWidgets.QComboBox(parent=self.message_frame)
        self.comboBox_prio.setGeometry(QtCore.QRect(20, 190, 491, 31))
        self.comboBox_prio.setStyleSheet("")
        self.comboBox_prio.setObjectName("comboBox_prio")
        self.comboBox_prio.addItem("")
        self.comboBox_prio.setItemText(0, "")
        self.comboBox_prio.addItem("")
        self.comboBox_prio.addItem("")
        self.comboBox_prio.addItem("")
        self.label_placeholder = QtWidgets.QLabel(parent=self.message_frame)
        self.label_placeholder.setGeometry(QtCore.QRect(30, 250, 271, 16))
        self.label_placeholder.setStyleSheet("#label_placeholder{\n"
"    color: gray;\n"
"    font-size: 12px;\n"
"}")
        self.label_placeholder.setObjectName("label_placeholder")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_header.setText(_translate("Form", "Compose Message"))
        self.btn_close.setText(_translate("Form", "X"))
        self.btn_cancel.setText(_translate("Form", "Cancel"))
        self.btn_send.setText(_translate("Form", "Send Message"))
        self.label.setText(_translate("Form", "To:"))
        self.label_2.setText(_translate("Form", "Subject:"))
        self.label_3.setText(_translate("Form", "Priority:"))
        self.label_4.setText(_translate("Form", "Message:"))
        self.comboBox_prio.setItemText(1, _translate("Form", "High Priority"))
        self.comboBox_prio.setItemText(2, _translate("Form", "Medium Priority"))
        self.comboBox_prio.setItemText(3, _translate("Form", "Low Priority"))
        self.label_placeholder.setText(_translate("Form", "Type your message here...."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
