# Generated by Django 5.2.5 on 2025-11-29 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('units', models.PositiveSmallIntegerField()),
                ('lec_hours', models.PositiveSmallIntegerField()),
                ('lab_hours', models.PositiveSmallIntegerField()),
                ('year_offered', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('term_offered', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer')], max_length=6)),
            ],
            options={
                'db_table': 'academics_course',
                'ordering': ['-curriculum', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Prerequisite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_title', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'schedule_block',
            },
        ),
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(unique=True)),
            ],
            options={
                'db_table': 'academics_academic_year',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['start_date'], name='academics_a_start_d_3bb5bc_idx'), models.Index(fields=['is_active'], name='academics_a_is_acti_039d4b_idx')],
                'constraints': [models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_ay_dates')],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='users.facultyprofile')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.course')),
            ],
            options={
                'db_table': 'academics_class',
                'ordering': ['-semester', 'course'],
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision_year', models.SmallIntegerField()),
                ('is_active', models.BooleanField()),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='users.program')),
            ],
            options={
                'db_table': 'academics_curriculum',
                'ordering': ['-revision_year'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='Academics.curriculum'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('enrolled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolling_officer', to=settings.AUTH_USER_MODEL)),
                ('enrolled_class', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='Academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='users.studentprofile')),
            ],
            options={
                'db_table': 'academics_enrollments',
                'ordering': ['-enrolled_at', 'enrolled_class'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', through='Academics.Enrollment', to='users.studentprofile'),
        ),
        migrations.CreateModel(
            name='GradingRubric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_period', models.CharField(choices=[('midterm', 'Midterm'), ('finals', 'Final Term')], max_length=7)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rubrics', to='Academics.class')),
            ],
            options={
                'db_table': 'academics_grading_rubric',
            },
        ),
        migrations.CreateModel(
            name='RubricComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='Academics.gradingrubric')),
            ],
            options={
                'db_table': 'academics_rubric_component',
            },
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('max_points', models.IntegerField()),
                ('due_date', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_assessments', to=settings.AUTH_USER_MODEL)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='Academics.class')),
                ('rubric_component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='Academics.rubriccomponent')),
            ],
            options={
                'db_table': 'academics_assessment',
            },
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_name', models.CharField(max_length=20)),
                ('additional_context', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('day_of_week', models.CharField(choices=[('sun', 'Sunday'), ('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday')], default='tue', max_length=3)),
                ('schedule_block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.scheduleblock')),
            ],
            options={
                'db_table': 'schedule_entry',
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.PositiveIntegerField()),
                ('is_published', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_scores', to='Academics.assessment')),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_scores', to='Academics.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='users.studentprofile')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'academics_score',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('year', models.CharField(choices=[('1', 'First Year'), ('2', 'Second Year'), ('3', 'Third Year'), ('4', 'Fourth Year')], max_length=1)),
                ('type', models.CharField(choices=[('lec', 'Lecture'), ('lab', 'Laboratory')], max_length=3)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='Academics.curriculum')),
            ],
            options={
                'db_table': 'academics_section',
                'ordering': ['-semester', 'name'],
            },
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.section'),
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('summer', 'Summer')], max_length=6)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(unique=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='semesters', to='Academics.academicyear')),
            ],
            options={
                'db_table': 'academics_semester',
                'ordering': ['-start_date'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='sem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.semester'),
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Academics.class')),
            ],
            options={
                'db_table': 'academics_topic',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='Academics.class')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_materials', to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materials', to='Academics.topic')),
            ],
            options={
                'db_table': 'academics_material',
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='Academics.topic'),
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('curriculum', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='Academics.curriculum')),
            ],
            options={
                'db_table': 'academics_track',
            },
        ),
        migrations.AddField(
            model_name='course',
            name='track',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='courses', to='Academics.track'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=7)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='users.studentprofile')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Academics.class')),
            ],
            options={
                'db_table': 'academics_attendance',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'class_instance'], name='academics_a_date_99004e_idx')],
                'constraints': [models.UniqueConstraint(fields=('class_instance', 'student', 'date'), name='one_attendance_per_student_per_session')],
            },
        ),
        migrations.AddConstraint(
            model_name='curriculum',
            constraint=models.UniqueConstraint(fields=('program', 'is_active'), name='one_active_curriculum_per_program'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_class', 'student'], name='academics_e_enrolle_ba3862_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('enrolled_class', 'student'), name='one_enrollment_per_class_per_student'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='unique_rubric_component'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='unique_student'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['start_date'], name='academics_s_start_d_91d619_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_80fb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year'], name='academics_s_academi_14aa40_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term'), name='unique_semester'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_sem_dates'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name', 'semester'], name='academics_s_name_36a02d_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'semester', 'type'), name='unique_section'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['faculty', 'semester'], name='academics_c_faculty_2d8b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('course', 'section', 'semester'), name='unique_course_section_per_class_per_sem'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year_offered', 'term_offered'], name='academics_c_year_of_d37b8f_idx'),
        ),
    ]
