# Generated by Django 5.2.5 on 2025-11-19 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='academicyear',
            table='academics_academic_year',
        ),
        migrations.AlterModelTable(
            name='assessment',
            table='academics_assessment',
        ),
        migrations.AlterModelTable(
            name='attendance',
            table='academics_attendance',
        ),
        migrations.AlterModelTable(
            name='class',
            table='academics_class',
        ),
        migrations.AlterModelTable(
            name='course',
            table='academics_course',
        ),
        migrations.AlterModelTable(
            name='curriculum',
            table='academics_curriculum',
        ),
        migrations.AlterModelTable(
            name='enrollees',
            table='academics_enrollees',
        ),
        migrations.AlterModelTable(
            name='gradingrubric',
            table='academics_grading_rubric',
        ),
        migrations.AlterModelTable(
            name='material',
            table='academics_material',
        ),
        migrations.AlterModelTable(
            name='rubriccomponent',
            table='academics_rubric_component',
        ),
        migrations.AlterModelTable(
            name='score',
            table='academics_score',
        ),
        migrations.AlterModelTable(
            name='section',
            table='academics_section',
        ),
        migrations.AlterModelTable(
            name='semester',
            table='academics_semester',
        ),
        migrations.AlterModelTable(
            name='topic',
            table='academics_topic',
        ),
        migrations.AlterModelTable(
            name='track',
            table='academics_track',
        ),
    ]
