# Generated by Django 5.2.5 on 2025-11-30 08:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='class',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_classes', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='lecture_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_classes', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='attendance',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.class'),
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.course'),
        ),
        migrations.AddField(
            model_name='curriculum',
            name='program',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculum', to='users.program'),
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='Academics.curriculum'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrolling_officer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='enrolled_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='class_enrollments', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='class',
            name='students',
            field=models.ManyToManyField(related_name='enrolled_classes', through='Academics.Enrollment', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='gradingrubric',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_rubrics', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='material',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.class'),
        ),
        migrations.AddField(
            model_name='material',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rubriccomponent',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='Academics.gradingrubric'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='Academics.rubriccomponent'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='schedule_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Academics.scheduleblock'),
        ),
        migrations.AddField(
            model_name='score',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='Academics.assessment'),
        ),
        migrations.AddField(
            model_name='score',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='score',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scores', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='score',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='Academics.curriculum'),
        ),
        migrations.AddField(
            model_name='class',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.section'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['start_date'], name='academics_s_start_d_91d619_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['is_active'], name='academics_s_is_acti_80fb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='semester',
            index=models.Index(fields=['academic_year'], name='academics_s_academi_a46b2d_idx'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('academic_year', 'term'), name='unique_semester'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('start_date', 'end_date'), name='unique_sem_dates'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='semester_start_before_end'),
        ),
        migrations.AddField(
            model_name='section',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='scheduleblock',
            name='sem_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='Academics.semester'),
        ),
        migrations.AddField(
            model_name='topic',
            name='class_instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='Academics.class'),
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.topic'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Academics.topic'),
        ),
        migrations.AddIndex(
            model_name='attendance',
            index=models.Index(fields=['date', 'class_instance'], name='academics_a_date_99004e_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendance',
            constraint=models.UniqueConstraint(fields=('class_instance', 'student', 'date'), name='one_attendance_per_student_per_session'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['year_offered', 'term_offered'], name='academics_c_year_of_d37b8f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['enrolled_class', 'student'], name='academics_e_enrolle_ba3862_idx'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('enrolled_class', 'student'), name='one_enrollment_per_class_per_student'),
        ),
        migrations.AddIndex(
            model_name='gradingrubric',
            index=models.Index(fields=['class_instance', 'academic_period'], name='academics_g_class_i_6d894d_idx'),
        ),
        migrations.AddConstraint(
            model_name='gradingrubric',
            constraint=models.UniqueConstraint(fields=('class_instance', 'academic_period'), name='unique_rubric_per_class_per_period'),
        ),
        migrations.AddConstraint(
            model_name='gradingrubric',
            constraint=models.CheckConstraint(condition=models.Q(('term_percentage__gte', 0), ('term_percentage__lte', 100)), name='valid_term_percentage'),
        ),
        migrations.AddIndex(
            model_name='rubriccomponent',
            index=models.Index(fields=['rubric'], name='academics_r_rubric__979561_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.UniqueConstraint(fields=('rubric', 'name'), name='unique_component_per_rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubriccomponent',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gt', 0), ('percentage__lte', 100)), name='valid_component_percentage'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['student', 'assessment'], name='academics_s_student_9d3a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['class_instance', 'is_published'], name='academics_s_class_i_8f9a4c_idx'),
        ),
        migrations.AddIndex(
            model_name='score',
            index=models.Index(fields=['assessment'], name='academics_s_assessm_7ea298_idx'),
        ),
        migrations.AddConstraint(
            model_name='score',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='one_score_per_student_per_assessment'),
        ),
        migrations.AddIndex(
            model_name='section',
            index=models.Index(fields=['name', 'semester'], name='academics_s_name_36a02d_idx'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'curriculum', 'semester', 'year', 'type'), name='unique_section'),
        ),
        migrations.AddIndex(
            model_name='class',
            index=models.Index(fields=['faculty', 'semester'], name='academics_c_faculty_2d8b6e_idx'),
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('course', 'section', 'semester'), name='unique_course_section_per_class_per_sem'),
        ),
        migrations.AddIndex(
            model_name='topic',
            index=models.Index(fields=['class_instance', 'topic_number'], name='academics_t_class_i_e0d9c4_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['class_instance', 'is_published'], name='academics_m_class_i_1fce14_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['topic'], name='academics_m_topic_i_e0f44b_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['class_instance', 'academic_period'], name='academics_a_class_i_a07fd2_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['rubric_component'], name='academics_a_rubric__d3e062_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['is_published'], name='academics_a_is_publ_4c667c_idx'),
        ),
    ]
