# Generated by Django 5.2.5 on 2025-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='academic_year',
            field=models.CharField(max_length=9),
        ),
        migrations.RenameIndex(
            model_name='semester',
            new_name='academics_s_academi_a46b2d_idx',
            old_name='academics_s_academi_14aa40_idx',
        ),
        migrations.DeleteModel(
            name='AcademicYear',
        ),
    ]
