# Generated by Django 5.2.5 on 2025-11-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0003_alter_semester_academic_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
