# Generated by Django 5.2.5 on 2025-11-22 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0004_alter_semester_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='curriculum',
        ),
        migrations.RemoveField(
            model_name='course',
            name='track',
        ),
        migrations.RemoveConstraint(
            model_name='curriculum',
            name='one_active_curriculum_per_program',
        ),
        migrations.DeleteModel(
            name='Track',
        ),
    ]
