# Generated by Django 5.2.5 on 2025-11-22 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0005_remove_track_curriculum_remove_course_track_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['is_active', '-start_date']},
        ),
    ]
