# Generated by Django 5.2.5 on 2025-11-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0006_alter_semester_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='semester_start_before_end'),
        ),
    ]
