# Generated by Django 5.2.5 on 2025-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0007_semester_semester_start_before_end'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=4),
        ),
    ]
