# Generated by Django 5.2.5 on 2025-11-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0008_alter_section_name'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'curriculum', 'semester', 'type'), name='unique_section'),
        ),
    ]
