# Generated by Django 5.2.5 on 2025-11-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academics', '0009_remove_section_unique_section_section_unique_section'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='section',
            name='unique_section',
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('name', 'curriculum', 'semester', 'year', 'type'), name='unique_section'),
        ),
    ]
