# Generated by Django 5.2.5 on 2025-12-04 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcements',
            fields=[
                ('announcement_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('publish_at', models.DateTimeField(blank=True, null=True)),
                ('expire_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(default='draft', max_length=30)),
                ('visibility', models.CharField(default='public', max_length=20)),
                ('priority', models.IntegerField(default=0)),
                ('is_pinned', models.BooleanField(default=False)),
                ('pinned_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'announcements',
            },
        ),
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('approval_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'approvals',
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'auth_user',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag_name', models.CharField(max_length=60, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tags',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementAudience',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=30)),
                ('scope_target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.announcements')),
            ],
            options={
                'db_table': 'announcement_audience',
            },
        ),
        migrations.AddField(
            model_name='announcements',
            name='approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Announcements.approvals'),
        ),
        migrations.AddField(
            model_name='approvals',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Announcements.authuser'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_author', to='Announcements.authuser'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_created', to='Announcements.authuser'),
        ),
        migrations.AddField(
            model_name='announcements',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='announcement_updated', to='Announcements.authuser'),
        ),
        migrations.CreateModel(
            name='AnnouncementReads',
            fields=[
                ('read_id', models.AutoField(primary_key=True, serialize=False)),
                ('has_read', models.BooleanField(default=False)),
                ('read_time', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.announcements')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.authuser')),
            ],
            options={
                'db_table': 'announcement_reads',
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('document_id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=1024)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=128, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visible', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('version', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.announcements')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Announcements.authuser')),
            ],
            options={
                'db_table': 'announcement_documents',
            },
        ),
        migrations.CreateModel(
            name='Reminders',
            fields=[
                ('reminder_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField(blank=True, null=True)),
                ('remind_at', models.DateTimeField(blank=True, null=True)),
                ('repeat_interval', models.CharField(blank=True, max_length=50, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_snoozable', models.BooleanField(default=True)),
                ('snooze_until', models.DateTimeField(blank=True, null=True)),
                ('visibility', models.CharField(default='private', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_author', to='Announcements.authuser')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_created', to='Announcements.authuser')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminder_updated', to='Announcements.authuser')),
            ],
            options={
                'db_table': 'reminders',
            },
        ),
        migrations.CreateModel(
            name='ReminderAudience',
            fields=[
                ('audience_id', models.AutoField(primary_key=True, serialize=False)),
                ('scope_type', models.CharField(max_length=30)),
                ('scope_target_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.reminders')),
            ],
            options={
                'db_table': 'reminder_audience',
            },
        ),
        migrations.CreateModel(
            name='ReminderAcknowledgements',
            fields=[
                ('ack_id', models.AutoField(primary_key=True, serialize=False)),
                ('acknowledged', models.BooleanField(default=False)),
                ('ack_time', models.DateTimeField(blank=True, null=True)),
                ('device_info', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.authuser')),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.reminders')),
            ],
            options={
                'db_table': 'reminder_acknowledgements',
            },
        ),
        migrations.CreateModel(
            name='AnnouncementTagMap',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.announcements')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Announcements.tags')),
            ],
            options={
                'db_table': 'announcement_tag_map',
            },
        ),
    ]
