# Form implementation generated from reading ui file 'admin_details.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(992, 750)
        self.msg_widget = QtWidgets.QWidget(parent=Form)
        self.msg_widget.setGeometry(QtCore.QRect(230, 10, 701, 361))
        self.msg_widget.setStyleSheet("#msg_widget {\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #dcdcdc;\n"
"}")
        self.msg_widget.setObjectName("msg_widget")
        self.admin_header = QtWidgets.QLabel(parent=self.msg_widget)
        self.admin_header.setGeometry(QtCore.QRect(20, 10, 551, 41))
        self.admin_header.setStyleSheet("#admin_header{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #FF0000;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.admin_header.setObjectName("admin_header")
        self.line_name = QtWidgets.QLineEdit(parent=self.msg_widget)
        self.line_name.setGeometry(QtCore.QRect(20, 90, 411, 41))
        self.line_name.setStyleSheet("#line_name {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 6px 10px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#line_name:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#line_name:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.line_name.setObjectName("line_name")
        self.admin_frame = QtWidgets.QFrame(parent=self.msg_widget)
        self.admin_frame.setGeometry(QtCore.QRect(20, 90, 431, 211))
        self.admin_frame.setStyleSheet("#admin_frame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #808080;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 10px 12px;        /* Comfortable inner spacing for messages */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#admin_frame:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#admin_frame:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.admin_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame.setObjectName("admin_frame")
        self.admin_frame_2 = QtWidgets.QFrame(parent=self.admin_frame)
        self.admin_frame_2.setGeometry(QtCore.QRect(350, 160, 431, 211))
        self.admin_frame_2.setStyleSheet("#admin_frame {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #808080;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 10px 12px;        /* Comfortable inner spacing for messages */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#admin_frame:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#admin_frame:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.admin_frame_2.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.admin_frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.admin_frame_2.setObjectName("admin_frame_2")
        self.widget_category = QtWidgets.QWidget(parent=self.msg_widget)
        self.widget_category.setGeometry(QtCore.QRect(470, 90, 211, 211))
        self.widget_category.setStyleSheet("#widget_category{\n"
"    background-color: #ffffff;\n"
"    border-radius: 12px;\n"
"    border: 1px solid #808080;\n"
"}")
        self.widget_category.setObjectName("widget_category")
        self.widget = QtWidgets.QWidget(parent=self.widget_category)
        self.widget.setGeometry(QtCore.QRect(10, 10, 181, 181))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_7 = QtWidgets.QLabel(parent=self.widget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(parent=self.widget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(parent=self.widget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.toolButton = QtWidgets.QToolButton(parent=self.msg_widget)
        self.toolButton.setGeometry(QtCore.QRect(660, 10, 22, 22))
        self.toolButton.setObjectName("toolButton")
        self.widget1 = QtWidgets.QWidget(parent=self.msg_widget)
        self.widget1.setGeometry(QtCore.QRect(21, 51, 327, 18))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_body_4 = QtWidgets.QLabel(parent=self.widget1)
        self.label_body_4.setObjectName("label_body_4")
        self.horizontalLayout.addWidget(self.label_body_4)
        self.label_body_3 = QtWidgets.QLabel(parent=self.widget1)
        self.label_body_3.setObjectName("label_body_3")
        self.horizontalLayout.addWidget(self.label_body_3)
        self.label_body_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_body_2.setObjectName("label_body_2")
        self.horizontalLayout.addWidget(self.label_body_2)
        self.widget2 = QtWidgets.QWidget(parent=self.msg_widget)
        self.widget2.setGeometry(QtCore.QRect(20, 310, 260, 26))
        self.widget2.setObjectName("widget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_assign = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_assign.setStyleSheet("#btn_assign{\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_assign:hover {\n"
"    background-color: #006420;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_assign:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_assign.setObjectName("btn_assign")
        self.horizontalLayout_2.addWidget(self.btn_assign)
        self.btn_mark = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_mark.setStyleSheet("#btn_mark{\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_mark:hover {\n"
"    background-color: #006420;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_mark:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"#btn_assign{\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_assign:hover {\n"
"    background-color: #006420;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_mark:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"#btn_assign{\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_assign:hover {\n"
"    background-color: #006420;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_assign:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_mark.setObjectName("btn_mark")
        self.horizontalLayout_2.addWidget(self.btn_mark)
        self.btn_archive = QtWidgets.QPushButton(parent=self.widget2)
        self.btn_archive.setStyleSheet("#btn_archive{\n"
"    color: #000000;              /* Red text color */\n"
"    border-radius: 4px;          /* Rounded corners */\n"
"    padding: 4px 12px;           /* Reduced padding for better fit */\n"
"    font-family: \"Segoe UI\";     /* Modern font */\n"
"    font-size: 12px;\n"
"    font-weight: 600;\n"
"    transition: all 0.2s ease;   /* Smooth hover transition */\n"
"}\n"
"\n"
"#btn_archive:hover {\n"
"    background-color: #808080;  /* Red hover background */\n"
"    color: #ffffff;             /* White text on hover */\n"
"}\n"
"\n"
"#btn_archive:pressed {\n"
"    background-color: #004d18;  /* Darker red when pressed */\n"
"    border-color: #8e1c1c;\n"
"}\n"
"")
        self.btn_archive.setObjectName("btn_archive")
        self.horizontalLayout_2.addWidget(self.btn_archive)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.admin_header.setText(_translate("Form", "CRITICAL: Unable to access course materials"))
        self.label.setText(_translate("Form", "Message details"))
        self.label_2.setText(_translate("Form", "Priority:"))
        self.label_3.setText(_translate("Form", "Status:"))
        self.label_7.setText(_translate("Form", "Department:"))
        self.label_8.setText(_translate("Form", "Category:"))
        self.label_9.setText(_translate("Form", "Date:"))
        self.toolButton.setText(_translate("Form", "x"))
        self.label_body_4.setText(_translate("Form", "10/20/2025"))
        self.label_body_3.setText(_translate("Form", "From: IT Department"))
        self.label_body_2.setText(_translate("Form", "To:sample123@cmu.edu.ph"))
        self.btn_assign.setText(_translate("Form", "Assign to"))
        self.btn_mark.setText(_translate("Form", "Mark resolved"))
        self.btn_archive.setText(_translate("Form", "Archive"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
