# Form implementation generated from reading ui file 'admin_home.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1333, 958)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget_total = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_total.setGeometry(QtCore.QRect(30, 20, 241, 151))
        self.widget_total.setStyleSheet("#widget_total {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_total:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_total:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_total.setObjectName("widget_total")
        self.label_total = QtWidgets.QLabel(parent=self.widget_total)
        self.label_total.setGeometry(QtCore.QRect(50, 0, 141, 41))
        self.label_total.setStyleSheet("#label_total{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_total.setObjectName("label_total")
        self.label_numbers = QtWidgets.QLabel(parent=self.widget_total)
        self.label_numbers.setGeometry(QtCore.QRect(60, 40, 151, 71))
        self.label_numbers.setStyleSheet("#label_numbers{\n"
"    font-family: Segoe UI;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_numbers.setObjectName("label_numbers")
        self.label_percent = QtWidgets.QLabel(parent=self.widget_total)
        self.label_percent.setGeometry(QtCore.QRect(20, 100, 201, 41))
        self.label_percent.setStyleSheet("QLabel#label_percent {\n"
"    background-color: #ffffff;   /* White background */\n"
"    color: #333333;              /* Text color */\n"
"    font-family: \"Montserrat\";   /* Font family */\n"
"    font-size: 11px;             /* Font size */\n"
"   \n"
"    padding: 4px 8px;            /* Inner spacing */\n"
"}\n"
"")
        self.label_percent.setObjectName("label_percent")
        self.widget_pending = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_pending.setGeometry(QtCore.QRect(520, 20, 241, 151))
        self.widget_pending.setStyleSheet("#widget_pending {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_pending:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_pending:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_pending.setObjectName("widget_pending")
        self.label_pend = QtWidgets.QLabel(parent=self.widget_pending)
        self.label_pend.setGeometry(QtCore.QRect(40, 0, 171, 41))
        self.label_pend.setStyleSheet("#label_pend {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_pend.setObjectName("label_pend")
        self.label_num_pend = QtWidgets.QLabel(parent=self.widget_pending)
        self.label_num_pend.setGeometry(QtCore.QRect(100, 50, 81, 51))
        self.label_num_pend.setStyleSheet("#label_num_pend{\n"
"    font-family: Segoe UI;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_num_pend.setObjectName("label_num_pend")
        self.label_response = QtWidgets.QLabel(parent=self.widget_pending)
        self.label_response.setGeometry(QtCore.QRect(30, 100, 191, 41))
        self.label_response.setStyleSheet("QLabel#label_response {\n"
"    background-color: #ffffff;   /* White background */\n"
"    color: #333333;              /* Text color */\n"
"    font-family: \"Montserrat\";   /* Font family */\n"
"    font-size: 11px;             /* Font size */\n"
"    padding: 4px 8px;            /* Inner spacing */\n"
"}\n"
"")
        self.label_response.setObjectName("label_response")
        self.widget_issues = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_issues.setGeometry(QtCore.QRect(280, 20, 231, 151))
        self.widget_issues.setStyleSheet("#widget_issues {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_issues:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_issues:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_issues.setObjectName("widget_issues")
        self.label_crit = QtWidgets.QLabel(parent=self.widget_issues)
        self.label_crit.setGeometry(QtCore.QRect(50, 0, 141, 41))
        self.label_crit.setStyleSheet("#label_crit {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_crit.setObjectName("label_crit")
        self.label_num_crit = QtWidgets.QLabel(parent=self.widget_issues)
        self.label_num_crit.setGeometry(QtCore.QRect(100, 40, 71, 71))
        self.label_num_crit.setStyleSheet("#label_num_crit{\n"
"    font-family: Segoe UI;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_num_crit.setObjectName("label_num_crit")
        self.label_action = QtWidgets.QLabel(parent=self.widget_issues)
        self.label_action.setGeometry(QtCore.QRect(40, 100, 171, 41))
        self.label_action.setStyleSheet("QLabel#label_action {\n"
"    background-color: #ffffff;   /* White background */\n"
"    color: #333333;              /* Text color */\n"
"    font-family: \"Montserrat\";   /* Font family */\n"
"    font-size: 11px;             /* Font size */\n"
"    padding: 4px 8px;            /* Inner spacing */\n"
"}\n"
"")
        self.label_action.setObjectName("label_action")
        self.widget_resolved = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_resolved.setGeometry(QtCore.QRect(770, 20, 241, 151))
        self.widget_resolved.setStyleSheet("#widget_resolved {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_resolved:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_resolved:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_resolved.setObjectName("widget_resolved")
        self.label_resolved = QtWidgets.QLabel(parent=self.widget_resolved)
        self.label_resolved.setGeometry(QtCore.QRect(60, 0, 231, 41))
        self.label_resolved.setStyleSheet("#label_resolved {\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_resolved.setObjectName("label_resolved")
        self.label_num_resolved = QtWidgets.QLabel(parent=self.widget_resolved)
        self.label_num_resolved.setGeometry(QtCore.QRect(100, 60, 61, 31))
        self.label_num_resolved.setStyleSheet("#label_num_resolved{\n"
"    font-family: Segoe UI;\n"
"    font-size: 30px;\n"
"    font-weight: bold;\n"
"    color: #000000;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.label_num_resolved.setObjectName("label_num_resolved")
        self.label_satisfaction = QtWidgets.QLabel(parent=self.widget_resolved)
        self.label_satisfaction.setGeometry(QtCore.QRect(60, 100, 171, 41))
        self.label_satisfaction.setStyleSheet("QLabel#label_satisfaction {\n"
"    background-color: #ffffff;   /* White background */\n"
"    color: #333333;              /* Text color */\n"
"    font-family: \"Montserrat\";   /* Font family */\n"
"    font-size: 11px;             /* Font size */\n"
"    padding: 4px 8px;            /* Inner spacing */\n"
"}\n"
"")
        self.label_satisfaction.setObjectName("label_satisfaction")
        self.widget_admin_category = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_admin_category.setGeometry(QtCore.QRect(20, 190, 191, 321))
        self.widget_admin_category.setStyleSheet("#widget_admin_category {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_admin_category:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_admin_category:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_admin_category.setObjectName("widget_admin_category")
        self.admin_label_2 = QtWidgets.QLabel(parent=self.widget_admin_category)
        self.admin_label_2.setGeometry(QtCore.QRect(20, 10, 151, 41))
        self.admin_label_2.setStyleSheet("#admin_label_2{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.admin_label_2.setObjectName("admin_label_2")
        self.layoutWidget = QtWidgets.QWidget(parent=self.widget_admin_category)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 60, 176, 148))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.btn_msg = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_msg.setStyleSheet("#btn_msg {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_msg:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_msg:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_msg.setObjectName("btn_msg")
        self.verticalLayout_2.addWidget(self.btn_msg)
        self.btn_crit = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_crit.setStyleSheet("#btn_crit {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_crit:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_crit:pressed {\n"
"    background-color: #004d18;\n"
"}\n"
"")
        self.btn_crit.setObjectName("btn_crit")
        self.verticalLayout_2.addWidget(self.btn_crit)
        self.btn_issue = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_issue.setStyleSheet("#btn_issue {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_issue:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_issue:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_issue.setObjectName("btn_issue")
        self.verticalLayout_2.addWidget(self.btn_issue)
        self.btn_tech = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_tech.setStyleSheet("#btn_tech {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_tech:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_tech:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_tech.setObjectName("btn_tech")
        self.verticalLayout_2.addWidget(self.btn_tech)
        self.widget_search = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_search.setGeometry(QtCore.QRect(220, 190, 791, 61))
        self.widget_search.setStyleSheet("#widget_search {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_search:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_search:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_search.setObjectName("widget_search")
        self.admin_search = QtWidgets.QLineEdit(parent=self.widget_search)
        self.admin_search.setGeometry(QtCore.QRect(10, 10, 411, 41))
        self.admin_search.setStyleSheet("#admin_search {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 10px 12px;        /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#admin_search:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#admin_search:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.admin_search.setObjectName("admin_search")
        self.widget_prio = QtWidgets.QComboBox(parent=self.widget_search)
        self.widget_prio.setGeometry(QtCore.QRect(430, 10, 101, 41))
        self.widget_prio.setStyleSheet("#widget_prio {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_prio:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_prio:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_prio.setObjectName("widget_prio")
        self.widget_prio.addItem("")
        self.widget_prio.addItem("")
        self.widget_prio.addItem("")
        self.widget_prio.addItem("")
        self.widget_stat = QtWidgets.QComboBox(parent=self.widget_search)
        self.widget_stat.setGeometry(QtCore.QRect(540, 11, 101, 41))
        self.widget_stat.setStyleSheet("#widget_stat {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_stat:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_stat:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_stat.setObjectName("widget_stat")
        self.widget_stat.addItem("")
        self.widget_stat.addItem("")
        self.widget_stat.addItem("")
        self.widget_dept = QtWidgets.QComboBox(parent=self.widget_search)
        self.widget_dept.setGeometry(QtCore.QRect(650, 10, 131, 41))
        self.widget_dept.setStyleSheet("#widget_dept {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_dept:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_dept:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_dept.setObjectName("widget_dept")
        self.widget_dept.addItem("")
        self.widget_dept.addItem("")
        self.widget_dept.addItem("")
        self.widget_dept.setItemText(2, "")
        self.search_hint = QtWidgets.QLabel(parent=self.widget_search)
        self.search_hint.setGeometry(QtCore.QRect(50, 20, 311, 16))
        self.search_hint.setStyleSheet("QLabel#search_hint {\n"
"    color: #999999;              /* Light gray text for placeholder */\n"
"    font-family: \"Montserrat\";   /* Modern font */\n"
"    font-size: 14px;             /* Font size */\n"
"    font-style: italic;\n"
"    background-color: transparent; /* Transparent background */\n"
"}\n"
"")
        self.search_hint.setObjectName("search_hint")
        self.widget_main = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_main.setGeometry(QtCore.QRect(220, 260, 791, 591))
        self.widget_main.setStyleSheet("#widget_main {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_main:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_main:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_main.setObjectName("widget_main")
        self.admin_label = QtWidgets.QLabel(parent=self.widget_main)
        self.admin_label.setGeometry(QtCore.QRect(10, 0, 211, 41))
        self.admin_label.setStyleSheet("#admin_label {\n"
"    font-family: Segoe UI;\n"
"    font-size: 18px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.admin_label.setObjectName("admin_label")
        self.line = QtWidgets.QFrame(parent=self.widget_main)
        self.line.setGeometry(QtCore.QRect(0, 40, 791, 16))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.widget_admin_action = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget_admin_action.setGeometry(QtCore.QRect(20, 530, 191, 321))
        self.widget_admin_action.setStyleSheet("#widget_admin_action {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_admin_action:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_admin_action:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"#widget_admin_category {\n"
"    background-color: #ffffff;\n"
"    border: 1px solid #dcdcdc;\n"
"    border-radius: 6px;        /* Slightly rounded corners */\n"
"    padding: 8px 12px;         /* Comfortable inner spacing */\n"
"    font-family: \"Montserrat\"; /* Modern font */\n"
"    font-size: 14px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"#widget_admin_category:focus {\n"
"    border: 1px solid #006420; /* Highlight border on focus */\n"
"    background-color: #f9f9f9; /* Slightly lighter background */\n"
"}\n"
"\n"
"#widget_admin_category:hover {\n"
"    border: 1px solid #b6b6b6; /* Subtle hover effect */\n"
"}\n"
"")
        self.widget_admin_action.setObjectName("widget_admin_action")
        self.admin_label_3 = QtWidgets.QLabel(parent=self.widget_admin_action)
        self.admin_label_3.setGeometry(QtCore.QRect(30, 10, 141, 41))
        self.admin_label_3.setStyleSheet("#admin_label_3{\n"
"    font-family: Segoe UI;\n"
"    font-size: 15px;\n"
"    font-weight: bold;\n"
"    color: #006420;\n"
"    letter-spacing: 1px;\n"
"}\n"
"")
        self.admin_label_3.setObjectName("admin_label_3")
        self.widget = QtWidgets.QWidget(parent=self.widget_admin_action)
        self.widget.setGeometry(QtCore.QRect(10, 60, 176, 148))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_system = QtWidgets.QPushButton(parent=self.widget)
        self.btn_system.setStyleSheet("#btn_system {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_system:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_system:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_system.setObjectName("btn_system")
        self.verticalLayout.addWidget(self.btn_system)
        self.btn_report = QtWidgets.QPushButton(parent=self.widget)
        self.btn_report.setStyleSheet("#btn_report {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_report:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_report:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_report.setObjectName("btn_report")
        self.verticalLayout.addWidget(self.btn_report)
        self.btn_settings = QtWidgets.QPushButton(parent=self.widget)
        self.btn_settings.setStyleSheet("#btn_settings {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_settings:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_settings:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_settings.setObjectName("btn_settings")
        self.verticalLayout.addWidget(self.btn_settings)
        self.btn_user = QtWidgets.QPushButton(parent=self.widget)
        self.btn_user.setStyleSheet("#btn_user {\n"
"    background-color: #ffffff;      /* Base color: plain white */\n"
"    color: #333333;                 /* Text color */\n"
"    border: none;                   /* No border for clean look */\n"
"    border-radius: 10px;            /* Slightly rounded corners */\n"
"    padding: 8px 22px;              /* Comfortable padding */\n"
"    font-family: \"Montserrat\", sans-serif; /* Modern font */\n"
"    font-size: 14px;\n"
"    font-weight: 600;\n"
"    cursor: pointer;                /* Pointer on hover */\n"
"    transition: all 0.25s ease;     /* Smooth transition */\n"
"}\n"
"\n"
"#btn_user:hover {\n"
"    background-color: #006420;      /* Green on hover */\n"
"    color: #ffffff;                 /* White text on hover */\n"
"}\n"
"\n"
"#btn_user:pressed {\n"
"    background-color: #004d18;      /* Darker green when pressed */\n"
"    color: #ffffff;\n"
"}\n"
"")
        self.btn_user.setObjectName("btn_user")
        self.verticalLayout.addWidget(self.btn_user)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1333, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_total.setText(_translate("MainWindow", "Total Messages"))
        self.label_numbers.setText(_translate("MainWindow", "1,247"))
        self.label_percent.setText(_translate("MainWindow", "12% more messages from last week"))
        self.label_pend.setText(_translate("MainWindow", "Pending Responses"))
        self.label_num_pend.setText(_translate("MainWindow", "23"))
        self.label_response.setText(_translate("MainWindow", "Average response time 2.4hrs"))
        self.label_crit.setText(_translate("MainWindow", "Critical Issues"))
        self.label_num_crit.setText(_translate("MainWindow", "5"))
        self.label_action.setText(_translate("MainWindow", "Requires immediate action"))
        self.label_resolved.setText(_translate("MainWindow", "Resolved Today"))
        self.label_num_resolved.setText(_translate("MainWindow", "67"))
        self.label_satisfaction.setText(_translate("MainWindow", "94% satisfaction rate"))
        self.admin_label_2.setText(_translate("MainWindow", "Message Category"))
        self.btn_msg.setText(_translate("MainWindow", "All messages"))
        self.btn_crit.setText(_translate("MainWindow", "Critical Issues"))
        self.btn_issue.setText(_translate("MainWindow", "System Issues"))
        self.btn_tech.setText(_translate("MainWindow", "Technical Support"))
        self.widget_prio.setItemText(0, _translate("MainWindow", "Priorities"))
        self.widget_prio.setItemText(1, _translate("MainWindow", "Normal"))
        self.widget_prio.setItemText(2, _translate("MainWindow", "Medium"))
        self.widget_prio.setItemText(3, _translate("MainWindow", "Urgent"))
        self.widget_stat.setItemText(0, _translate("MainWindow", "Status"))
        self.widget_stat.setItemText(1, _translate("MainWindow", "Pending"))
        self.widget_stat.setItemText(2, _translate("MainWindow", "Resolved"))
        self.widget_dept.setItemText(0, _translate("MainWindow", "Departments"))
        self.widget_dept.setItemText(1, _translate("MainWindow", "IT "))
        self.search_hint.setText(_translate("MainWindow", "Search messages,users,etc"))
        self.admin_label.setText(_translate("MainWindow", "System Messages"))
        self.admin_label_3.setText(_translate("MainWindow", "Admin Actions"))
        self.btn_system.setText(_translate("MainWindow", "System Broadcast"))
        self.btn_report.setText(_translate("MainWindow", "Generate Reports"))
        self.btn_settings.setText(_translate("MainWindow", "System Settings"))
        self.btn_user.setText(_translate("MainWindow", "User Management"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
