# Generated by Django 5.2.5 on 2025-11-10 13:11

import apps.Documents.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documenttag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='documenttag',
            name='document',
        ),
        migrations.RemoveField(
            model_name='documenttag',
            name='tag',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AlterModelOptions(
            name='documentdownloads',
            options={'ordering': ['-downloaded_at'], 'verbose_name_plural': 'Document Downloads'},
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='documents', to='Documents.tag'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='Documents.category'),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='Documents.documenttype'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_extension',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_path',
            field=models.FileField(upload_to=apps.Documents.models.document_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='max_file_size_mb',
            field=models.IntegerField(default=10, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='documenttype',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_featured'], name='documents_is_feat_5915ef_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_0426e4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_title_3f6c9c_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='positive_file_size'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='one_current_version_per_document'),
        ),
        migrations.DeleteModel(
            name='DocumentTag',
        ),
    ]
