# Generated by Django 5.2.5 on 2025-12-04 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['display_order', 'slug'], name='categories_display_ce0393_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='Documents.category'),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='document',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='approval', to='Documents.document'),
        ),
        migrations.AddField(
            model_name='documentapproval',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approvalhistory',
            name='approval',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='Documents.documentapproval'),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='Documents.document'),
        ),
        migrations.AddIndex(
            model_name='documenttype',
            index=models.Index(fields=['slug'], name='document_ty_slug_5e6bb8_idx'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='documents', to='Documents.documenttype'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='Documents.document'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='category',
            field=models.ForeignKey(help_text='Root category for this folder', on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='Documents.category'),
        ),
        migrations.AddField(
            model_name='folder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folder',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='Documents.folder'),
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder where this document is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Documents.folder'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='Documents.folder'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderrolepermission',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_role_permissions', to='Documents.folder'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['content_type', 'object_id', '-created_at'], name='activity_lo_content_f80459_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['user', '-created_at'], name='activity_lo_user_id_b8c999_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', '-created_at'], name='activity_lo_action_78df1b_idx'),
        ),
        migrations.AddIndex(
            model_name='activitylog',
            index=models.Index(fields=['action', 'content_type', '-created_at'], name='activity_lo_action_5deb49_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['status'], name='document_ap_status_a613f5_idx'),
        ),
        migrations.AddIndex(
            model_name='documentapproval',
            index=models.Index(fields=['reviewed_by'], name='document_ap_reviewe_a60420_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['document'], name='document_pe_documen_6c92bd_idx'),
        ),
        migrations.AddIndex(
            model_name='documentpermission',
            index=models.Index(fields=['role'], name='document_pe_role_e208a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentpermission',
            unique_together={('document', 'role')},
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['document'], name='document_ve_documen_c337ce_idx'),
        ),
        migrations.AddIndex(
            model_name='documentversion',
            index=models.Index(fields=['version_number'], name='document_ve_version_d61733_idx'),
        ),
        migrations.AddConstraint(
            model_name='documentversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('document',), name='one_current_version_per_document'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_number')},
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='folders_parent__95398b_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['category'], name='folders_categor_57568d_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_by'], name='folders_created_a20dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['deleted_at'], name='folders_deleted_66c01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['category', '-uploaded_at'], name='documents_categor_4d860a_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by'], name='documents_uploade_aad805_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_active'], name='documents_is_acti_a803bb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['is_featured'], name='documents_is_feat_5915ef_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='documents_documen_0426e4_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['title'], name='documents_title_3f6c9c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['deleted_at'], name='documents_deleted_5f96ec_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='documents_folder__5c7d69_idx'),
        ),
        migrations.AddConstraint(
            model_name='document',
            constraint=models.CheckConstraint(condition=models.Q(('file_size__gte', 0)), name='positive_file_size'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['folder'], name='folder_perm_folder__36717c_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['user'], name='folder_perm_user_id_71e281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('folder', 'user')},
        ),
        migrations.AddIndex(
            model_name='folderrolepermission',
            index=models.Index(fields=['folder'], name='folder_role_folder__81d200_idx'),
        ),
        migrations.AddIndex(
            model_name='folderrolepermission',
            index=models.Index(fields=['role'], name='folder_role_role_afc0bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderrolepermission',
            unique_together={('folder', 'role')},
        ),
    ]
