# Generated by Django 5.2.5 on 2025-12-01 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_activitylog_delete_documentdownloads_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('can_view', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'folder_permissions',
            },
        ),
        migrations.CreateModel(
            name='FolderRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], max_length=50)),
                ('can_view', models.BooleanField(default=True)),
                ('can_upload', models.BooleanField(default=False)),
                ('can_edit', models.BooleanField(default=False)),
                ('can_delete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'folder_role_permissions',
            },
        ),
        migrations.RemoveField(
            model_name='document',
            name='tags',
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='can_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='documentpermission',
            name='can_edit',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentpermission',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('student', 'Student'), ('faculty', 'Faculty'), ('staff', 'Staff')], default='student', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True, help_text='If False, only users with explicit permissions can access')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(help_text='Root category for this folder', on_delete=django.db.models.deletion.PROTECT, related_name='folders', to='Documents.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_folders', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='Documents.folder')),
            ],
            options={
                'db_table': 'folders',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='document',
            name='folder',
            field=models.ForeignKey(blank=True, help_text='Folder where this document is stored', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='Documents.folder'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['deleted_at'], name='documents_deleted_5f96ec_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['folder'], name='documents_folder__5c7d69_idx'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='Documents.folder'),
        ),
        migrations.AddField(
            model_name='folderpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='folderrolepermission',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_role_permissions', to='Documents.folder'),
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['parent'], name='folders_parent__95398b_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['category'], name='folders_categor_57568d_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['created_by'], name='folders_created_a20dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='folder',
            index=models.Index(fields=['deleted_at'], name='folders_deleted_66c01d_idx'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['folder'], name='folder_perm_folder__36717c_idx'),
        ),
        migrations.AddIndex(
            model_name='folderpermission',
            index=models.Index(fields=['user'], name='folder_perm_user_id_71e281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderpermission',
            unique_together={('folder', 'user')},
        ),
        migrations.AddIndex(
            model_name='folderrolepermission',
            index=models.Index(fields=['folder'], name='folder_role_folder__81d200_idx'),
        ),
        migrations.AddIndex(
            model_name='folderrolepermission',
            index=models.Index(fields=['role'], name='folder_role_role_afc0bc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='folderrolepermission',
            unique_together={('folder', 'role')},
        ),
    ]
