# Generated by Django 5.2.5 on 2025-11-10 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Academics', '0001_initial'),
        ('users', '0002_remove_facultyprofile_id_remove_studentprofile_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventScheduleBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'event_schedule_blocks',
            },
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('venue', models.CharField(max_length=100)),
                ('event_status', models.CharField(choices=[('prpsd', 'proposed'), ('aprvd', 'approved'), ('cmplt', 'completed'), ('resch', 'rescheduled')], default='prpsd', max_length=5)),
                ('sem_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Academics.semester')),
            ],
        ),
        migrations.CreateModel(
            name='EventAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField()),
                ('time_out', models.DateTimeField()),
                ('notes', models.CharField(max_length=100)),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile')),
            ],
            options={
                'db_table': 'event_attendance',
            },
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('creation_date', models.DateTimeField()),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventschedule'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_schedule_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.eventscheduleblock'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventtype'),
        ),
        migrations.CreateModel(
            name='EventApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=100, null=True)),
                ('approver_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.facultyprofile')),
                ('event_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event')),
            ],
            options={
                'db_table': 'event_approvals',
                'constraints': [models.UniqueConstraint(fields=('event_id',), name='events_approved_only_once')],
            },
        ),
    ]
