# Generated by Django 5.2.5 on 2025-11-30 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'application_details',
            },
        ),
        migrations.CreateModel(
            name='Positions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rank', models.PositiveSmallIntegerField(default=100)),
                ('description', models.TextField()),
            ],
            options={
                'db_table': 'positions',
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('logo_path', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('org_level', models.CharField(choices=[('col', 'College'), ('prog', 'Program')], max_length=7)),
                ('main_org', models.ManyToManyField(blank=True, to='Organizations.organization')),
            ],
            options={
                'db_table': 'organization ',
            },
        ),
        migrations.CreateModel(
            name='MembershipApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(choices=[('acc', 'Accepted'), ('rej', 'Rejected'), ('pen', 'Pending')], default='pen', max_length=3)),
                ('application_details_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.applicationdetails')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
            ],
            options={
                'db_table': 'membership_application',
            },
        ),
        migrations.CreateModel(
            name='OrganizationMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('joined_at', models.DateField(auto_now_add=True)),
                ('organization_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile')),
            ],
            options={
                'db_table': 'organization_members',
                'unique_together': {('organization_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='OrgAdviserTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('pri', 'Primary'), ('sec', 'Secondary')], max_length=12)),
                ('semester', models.IntegerField()),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('adviser', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_advisory', to='users.facultyprofile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('role', 'pri')), fields=('org', 'semester', 'role'), name='one_primary_adviser_per_semester'), models.UniqueConstraint(fields=('org', 'adviser', 'semester', 'role'), name='uniq_adviser_role_period')],
            },
        ),
        migrations.CreateModel(
            name='OfficerTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_term', models.DateField()),
                ('end_term', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.studentprofile')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organization')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organizationmembers')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='Organizations.positions')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('start_term__lt', models.F('end_term')), ('end_term__isnull', True), _connector='OR'), name='officer_term_order'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org', 'position', 'status'), name='one_active_officer_per_position')],
            },
        ),
        migrations.CreateModel(
            name='OrgActivation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='Organizations.organization')),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_activations', to='Organizations.semester')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('org', 'semester'), name='uniq_org_semester_activation'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org', 'semester', 'status'), name='one_active_activation_per_period')],
            },
        ),
    ]
