# Generated by Django 5.2.5 on 2025-11-30 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='membershipapplication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='orgadviserterm',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_advisory', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_org',
            field=models.ManyToManyField(blank=True, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgadviserterm',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgactivation',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activations', to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organizationmembers'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='Organizations.positions'),
        ),
        migrations.AddField(
            model_name='orgactivation',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_activations', to='Organizations.semester'),
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'pri')), fields=('org', 'semester', 'role'), name='one_primary_adviser_per_semester'),
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(fields=('org', 'adviser', 'semester', 'role'), name='uniq_adviser_role_period'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembers',
            unique_together={('organization_id', 'user_id')},
        ),
        migrations.AddConstraint(
            model_name='officerterm',
            constraint=models.CheckConstraint(condition=models.Q(('start_term__lt', models.F('end_term')), ('end_term__isnull', True), _connector='OR'), name='officer_term_order'),
        ),
        migrations.AddConstraint(
            model_name='officerterm',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org', 'position', 'status'), name='one_active_officer_per_position'),
        ),
        migrations.AddConstraint(
            model_name='orgactivation',
            constraint=models.UniqueConstraint(fields=('org', 'semester'), name='uniq_org_semester_activation'),
        ),
        migrations.AddConstraint(
            model_name='orgactivation',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org', 'semester', 'status'), name='one_active_activation_per_period'),
        ),
    ]
