# Generated by Django 5.2.5 on 2025-12-08 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapproval',
            name='approver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='eventapproval',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_schedule_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventscheduleblock'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventscheduleblock'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventtype'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='application_details_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.applicationdetails'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orgadviserterm',
            name='adviser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='org_advisory', to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='organization',
            name='main_org',
            field=models.ManyToManyField(blank=True, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='orgadviserterm',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='org',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='membershipapplication',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='kicked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kicked_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officer_terms', to='Organizations.organizationmembers'),
        ),
        migrations.AddField(
            model_name='officerterm',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='Organizations.positions'),
        ),
        migrations.AddConstraint(
            model_name='eventapproval',
            constraint=models.UniqueConstraint(fields=('event_id',), name='events_approved_only_once'),
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'pri')), fields=('org', 'role'), name='one_primary_adviser'),
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(fields=('org', 'adviser', 'role'), name='uniq_adviser_role_period'),
        ),
        migrations.AlterUniqueTogether(
            name='organizationmembers',
            unique_together={('organization_id', 'user_id')},
        ),
        migrations.AddConstraint(
            model_name='officerterm',
            constraint=models.CheckConstraint(condition=models.Q(('start_term__lt', models.F('end_term')), ('end_term__isnull', True), _connector='OR'), name='officer_term_order'),
        ),
        migrations.AddConstraint(
            model_name='officerterm',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('org', 'position', 'status'), name='one_active_officer_per_position'),
        ),
    ]
