# Generated by Django 5.2.5 on 2025-11-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='applicationdetails',
            table=None,
        ),
        migrations.AlterModelTable(
            name='membershipapplication',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organization',
            table=None,
        ),
        migrations.AlterModelTable(
            name='organizationmembers',
            table=None,
        ),
        migrations.AlterModelTable(
            name='positions',
            table=None,
        ),
    ]
