# Generated by Django 5.2.5 on 2025-11-30 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventapproval',
            name='approver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.facultyprofile'),
        ),
        migrations.AddField(
            model_name='eventapproval',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventattendance',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.event'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.studentprofile'),
        ),
        migrations.AddField(
            model_name='eventschedule',
            name='event_schedule_block_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventscheduleblock'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_schedule_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventscheduleblock'),
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Organizations.eventtype'),
        ),
        migrations.AddConstraint(
            model_name='eventapproval',
            constraint=models.UniqueConstraint(fields=('event_id',), name='events_approved_only_once'),
        ),
    ]
