# Generated by Django 5.2.5 on 2025-11-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='objectives',
            field=models.TextField(default='None'),
        ),
    ]
