# Generated by Django 5.2.5 on 2025-11-30 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0003_organization_objectives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='objectives',
            field=models.TextField(blank=True, default=''),
        ),
    ]
