# Generated by Django 5.2.5 on 2025-12-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0005_alter_officerterm_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officerterm',
            name='end_term',
            field=models.DateField(),
        ),
    ]
