# Generated by Django 5.2.5 on 2025-12-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0006_alter_officerterm_end_term'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationmembers',
            name='is_kick',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationmembers',
            name='kicked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kicked_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
