# Generated by Django 5.2.5 on 2025-12-02 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0007_organizationmembers_is_kick_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='officerterm',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='officer_photos/'),
        ),
    ]
