# Generated by Django 5.2.5 on 2025-12-02 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0008_officerterm_photo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrgActivation',
        ),
        migrations.DeleteModel(
            name='Semester',
        ),
    ]
