# Generated by Django 5.2.5 on 2025-12-02 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0009_delete_orgactivation_delete_semester'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='orgadviserterm',
            name='one_primary_adviser_per_semester',
        ),
        migrations.RemoveConstraint(
            model_name='orgadviserterm',
            name='uniq_adviser_role_period',
        ),
        migrations.RemoveField(
            model_name='orgadviserterm',
            name='semester',
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'pri')), fields=('org', 'role'), name='one_primary_adviser'),
        ),
        migrations.AddConstraint(
            model_name='orgadviserterm',
            constraint=models.UniqueConstraint(fields=('org', 'adviser', 'role'), name='uniq_adviser_role_period'),
        ),
    ]
