# Generated by Django 5.2.5 on 2025-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0010_remove_orgadviserterm_one_primary_adviser_per_semester_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.SmallIntegerField()),
                ('action', models.CharField(choices=[('kicked', 'Kicked'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('archived', 'Archived'), ('edited', 'Edited'), ('created', 'Created')], max_length=20)),
                ('target_id', models.SmallIntegerField()),
            ],
        ),
    ]
