# Generated by Django 5.2.5 on 2025-12-03 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0011_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Log',
        ),
    ]
