# Generated by Django 5.2.5 on 2025-12-03 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0012_delete_log'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.SmallIntegerField()),
                ('action', models.CharField(choices=[('kicked', 'Kicked'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('archived', 'Archived'), ('edited', 'Edited'), ('created', 'Created')], max_length=20)),
                ('target_id', models.SmallIntegerField()),
                ('target_type', models.CharField(max_length=100)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
