# Generated by Django 5.2.5 on 2025-12-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0013_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='action',
            field=models.CharField(choices=[('kicked', 'Kicked'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('applied', 'Applied'), ('archived', 'Archived'), ('edited', 'Edited'), ('created', 'Created'), ('activated', 'Activated'), ('deactivate', 'Deactivate')], max_length=20),
        ),
    ]
