# Generated by Django 5.2.5 on 2025-12-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0014_alter_log_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
