# Generated by Django 5.2.5 on 2025-12-03 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Organizations', '0015_organization_is_active_organization_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
