# Form implementation generated from reading ui file 'bubble_reciever.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bubble_reciever(object):
    def setupUi(self, bubble_reciever):
        bubble_reciever.setObjectName("bubble_reciever")
        bubble_reciever.resize(400, 300)
        self.bubble_left = QtWidgets.QWidget(parent=bubble_reciever)
        self.bubble_left.setGeometry(QtCore.QRect(60, 30, 270, 231))
        self.bubble_left.setStyleSheet("QWidget#bubble_left {\n"
"    background-color: #e0e0e0;     /* Light gray for receiver */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: black;\n"
"    max-width: 250px;\n"
"}\n"
"")
        self.bubble_left.setObjectName("bubble_left")

        self.retranslateUi(bubble_reciever)
        QtCore.QMetaObject.connectSlotsByName(bubble_reciever)

    def retranslateUi(self, bubble_reciever):
        _translate = QtCore.QCoreApplication.translate
        bubble_reciever.setWindowTitle(_translate("bubble_reciever", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bubble_reciever = QtWidgets.QWidget()
    ui = Ui_bubble_reciever()
    ui.setupUi(bubble_reciever)
    bubble_reciever.show()
    sys.exit(app.exec())
