# Form implementation generated from reading ui file 'bubble_sender.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_bubble_sender(object):
    def setupUi(self, bubble_sender):
        bubble_sender.setObjectName("bubble_sender")
        bubble_sender.resize(400, 397)
        self.bubble_right = QtWidgets.QWidget(parent=bubble_sender)
        self.bubble_right.setGeometry(QtCore.QRect(60, 60, 270, 231))
        self.bubble_right.setStyleSheet("QWidget#bubble_right{\n"
"    background-color: #76a979;     /* Greenish color */\n"
"    border-radius: 10px;\n"
"    padding: 10px;\n"
"    color: white;\n"
"    max-width: 250px;\n"
"}")
        self.bubble_right.setObjectName("bubble_right")

        self.retranslateUi(bubble_sender)
        QtCore.QMetaObject.connectSlotsByName(bubble_sender)

    def retranslateUi(self, bubble_sender):
        _translate = QtCore.QCoreApplication.translate
        bubble_sender.setWindowTitle(_translate("bubble_sender", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    bubble_sender = QtWidgets.QWidget()
    ui = Ui_bubble_sender()
    ui.setupUi(bubble_sender)
    bubble_sender.show()
    sys.exit(app.exec())
